package com.mwyq.dao;

import com.mwyq.model.EntityNewsRelation;
import com.mwyq.model.EntityNewsRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EntityNewsRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_news_relation
     *
     * @mbggenerated
     */
    int countByExample(EntityNewsRelationExample example);
    
    List<EntityNewsRelation> getEntityNewsRelByNewId(@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_news_relation
     *
     * @mbggenerated
     */
    int deleteByExample(EntityNewsRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_news_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_news_relation
     *
     * @mbggenerated
     */
    int insert(EntityNewsRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_news_relation
     *
     * @mbggenerated
     */
    int insertSelective(EntityNewsRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_news_relation
     *
     * @mbggenerated
     */
    List<EntityNewsRelation> selectByExample(EntityNewsRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_news_relation
     *
     * @mbggenerated
     */
    EntityNewsRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_news_relation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EntityNewsRelation record, @Param("example") EntityNewsRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_news_relation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EntityNewsRelation record, @Param("example") EntityNewsRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_news_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EntityNewsRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_news_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EntityNewsRelation record);
}