package com.mwyq.dao;

import com.mwyq.model.StatisticEntity;
import com.mwyq.model.Topic;
import com.mwyq.model.TopicAndEntity;
import com.mwyq.model.TopicExample;
import com.mwyq.model.TwitterGroup;
import com.mwyq.model.topicEntity;
import com.mwyq.model.topicNumModel;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    int countByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    int deleteByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String topic_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    int insert(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    int insertSelective(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    List<Topic> selectByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    Topic selectByPrimaryKey(String topic_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Topic record, @Param("example") TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Topic record, @Param("example") TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Topic record);
    
    List<Topic> getHotTopics();
	
	/*
	 * 浠巔age椤靛紑濮�,鑾峰彇count鏉℃暟鎹�
	 */
	List<Topic> getTopics(@Param("offset") int offset,@Param("limit") int limit,@Param("lang") String lang);

	int selectCount();
	/**
	 * 鍘嗗彶璇濋鎺掕
	 * @param limit
	 * @return
	 */
	List<Topic> getHistoryTopics(@Param("limit") int limit,@Param("lang") String lang);
	
	Topic getLastTopic(@Param("lang") String lang);
	
	
    List<Topic> getCustomTopic(@Param("keyWord") String keyWord,@Param("lang") String lang);
    
    List<topicNumModel> getTopicNum(@Param("lang") String lang);
    
    List<topicEntity> getTopicEntity(@Param("id") String id);
    
    List<Topic> getHistoryTopicByYear(@Param("lang") String lang);
    List<Topic> getHistoryTopicByMonth(@Param("lang") String lang);
    List<Topic> getHistoryTopicByWeek(@Param("lang") String lang);
    
    List<TwitterGroup> getTwitterGroup();
    
    List<TopicAndEntity> getAllTopicAndEntityData();
    void insertLocStat(List<StatisticEntity> locStatList);
    void insertOrgStat(List<StatisticEntity> orgStatList);
    void insertPerStat(List<StatisticEntity> perStatList);
    void turncateLocStat();
    void turncatePerStat();
    void turncateOrgStat();
}