package com.mwyq.dao;

import com.mwyq.model.TopicTopicRelation;
import com.mwyq.model.TopicTopicRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TopicTopicRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_topic_relation
     *
     * @mbggenerated
     */
    int countByExample(TopicTopicRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_topic_relation
     *
     * @mbggenerated
     */
    int deleteByExample(TopicTopicRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_topic_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_topic_relation
     *
     * @mbggenerated
     */
    int insert(TopicTopicRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_topic_relation
     *
     * @mbggenerated
     */
    int insertSelective(TopicTopicRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_topic_relation
     *
     * @mbggenerated
     */
    List<TopicTopicRelation> selectByExample(TopicTopicRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_topic_relation
     *
     * @mbggenerated
     */
    TopicTopicRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_topic_relation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TopicTopicRelation record, @Param("example") TopicTopicRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_topic_relation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TopicTopicRelation record, @Param("example") TopicTopicRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_topic_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TopicTopicRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_topic_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TopicTopicRelation record);
}