package com.mwyq.dao;

import com.mwyq.model.StatisticEntity;
import com.mwyq.model.Topicminingdistribution;
import com.mwyq.model.TopicminingdistributionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TopicminingdistributionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicminingdistribution
     *
     * @mbggenerated
     */
    int countByExample(TopicminingdistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicminingdistribution
     *
     * @mbggenerated
     */
    int deleteByExample(TopicminingdistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicminingdistribution
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicminingdistribution
     *
     * @mbggenerated
     */
    int insert(Topicminingdistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicminingdistribution
     *
     * @mbggenerated
     */
    int insertSelective(Topicminingdistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicminingdistribution
     *
     * @mbggenerated
     */
    List<Topicminingdistribution> selectByExample(TopicminingdistributionExample example);
    List<Topicminingdistribution> getOrganizeStatData(TopicminingdistributionExample example);
    List<Topicminingdistribution> getLocationStatData(TopicminingdistributionExample example);
    List<Topicminingdistribution> getPeopleStatData(TopicminingdistributionExample example);
    
    /**
     *jinbo
     *按话题id和实体类型查询
     */
    List<Topicminingdistribution> selectByTopicAndType(TopicminingdistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicminingdistribution
     *
     * @mbggenerated
     */
    Topicminingdistribution selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicminingdistribution
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Topicminingdistribution record, @Param("example") TopicminingdistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicminingdistribution
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Topicminingdistribution record, @Param("example") TopicminingdistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicminingdistribution
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Topicminingdistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicminingdistribution
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Topicminingdistribution record);
}