package com.mwyq.dao;

import com.mwyq.model.TopicDocumentRelation;
import com.mwyq.model.TopicDocumentRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TopicDocumentRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_document_relation
     *
     * @mbggenerated
     */
    int countByExample(TopicDocumentRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_document_relation
     *
     * @mbggenerated
     */
    int deleteByExample(TopicDocumentRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_document_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_document_relation
     *
     * @mbggenerated
     */
    int insert(TopicDocumentRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_document_relation
     *
     * @mbggenerated
     */
    int insertSelective(TopicDocumentRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_document_relation
     *
     * @mbggenerated
     */
    List<TopicDocumentRelation> selectByExample(TopicDocumentRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_document_relation
     *
     * @mbggenerated
     */
    TopicDocumentRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_document_relation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TopicDocumentRelation record, @Param("example") TopicDocumentRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_document_relation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TopicDocumentRelation record, @Param("example") TopicDocumentRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_document_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TopicDocumentRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_document_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TopicDocumentRelation record);
}