package com.mwyq.model;

import java.util.ArrayList;
import java.util.List;

public class EntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entity
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entity
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entity
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbggenerated
     */
    public EntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entity
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEntity_idIsNull() {
            addCriterion("entity_id is null");
            return (Criteria) this;
        }

        public Criteria andEntity_idIsNotNull() {
            addCriterion("entity_id is not null");
            return (Criteria) this;
        }

        public Criteria andEntity_idEqualTo(Integer value) {
            addCriterion("entity_id =", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idNotEqualTo(Integer value) {
            addCriterion("entity_id <>", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idGreaterThan(Integer value) {
            addCriterion("entity_id >", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("entity_id >=", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idLessThan(Integer value) {
            addCriterion("entity_id <", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idLessThanOrEqualTo(Integer value) {
            addCriterion("entity_id <=", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idIn(List<Integer> values) {
            addCriterion("entity_id in", values, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idNotIn(List<Integer> values) {
            addCriterion("entity_id not in", values, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idBetween(Integer value1, Integer value2) {
            addCriterion("entity_id between", value1, value2, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idNotBetween(Integer value1, Integer value2) {
            addCriterion("entity_id not between", value1, value2, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_typeIsNull() {
            addCriterion("entity_type is null");
            return (Criteria) this;
        }

        public Criteria andEntity_typeIsNotNull() {
            addCriterion("entity_type is not null");
            return (Criteria) this;
        }

        public Criteria andEntity_typeEqualTo(String value) {
            addCriterion("entity_type =", value, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeNotEqualTo(String value) {
            addCriterion("entity_type <>", value, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeGreaterThan(String value) {
            addCriterion("entity_type >", value, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeGreaterThanOrEqualTo(String value) {
            addCriterion("entity_type >=", value, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeLessThan(String value) {
            addCriterion("entity_type <", value, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeLessThanOrEqualTo(String value) {
            addCriterion("entity_type <=", value, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeLike(String value) {
            addCriterion("entity_type like", value, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeNotLike(String value) {
            addCriterion("entity_type not like", value, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeIn(List<String> values) {
            addCriterion("entity_type in", values, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeNotIn(List<String> values) {
            addCriterion("entity_type not in", values, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeBetween(String value1, String value2) {
            addCriterion("entity_type between", value1, value2, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeNotBetween(String value1, String value2) {
            addCriterion("entity_type not between", value1, value2, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_keyIsNull() {
            addCriterion("entity_key is null");
            return (Criteria) this;
        }

        public Criteria andEntity_keyIsNotNull() {
            addCriterion("entity_key is not null");
            return (Criteria) this;
        }

        public Criteria andEntity_keyEqualTo(String value) {
            addCriterion("entity_key =", value, "entity_key");
            return (Criteria) this;
        }

        public Criteria andEntity_keyNotEqualTo(String value) {
            addCriterion("entity_key <>", value, "entity_key");
            return (Criteria) this;
        }

        public Criteria andEntity_keyGreaterThan(String value) {
            addCriterion("entity_key >", value, "entity_key");
            return (Criteria) this;
        }

        public Criteria andEntity_keyGreaterThanOrEqualTo(String value) {
            addCriterion("entity_key >=", value, "entity_key");
            return (Criteria) this;
        }

        public Criteria andEntity_keyLessThan(String value) {
            addCriterion("entity_key <", value, "entity_key");
            return (Criteria) this;
        }

        public Criteria andEntity_keyLessThanOrEqualTo(String value) {
            addCriterion("entity_key <=", value, "entity_key");
            return (Criteria) this;
        }

        public Criteria andEntity_keyLike(String value) {
            addCriterion("entity_key like", value, "entity_key");
            return (Criteria) this;
        }

        public Criteria andEntity_keyNotLike(String value) {
            addCriterion("entity_key not like", value, "entity_key");
            return (Criteria) this;
        }

        public Criteria andEntity_keyIn(List<String> values) {
            addCriterion("entity_key in", values, "entity_key");
            return (Criteria) this;
        }

        public Criteria andEntity_keyNotIn(List<String> values) {
            addCriterion("entity_key not in", values, "entity_key");
            return (Criteria) this;
        }

        public Criteria andEntity_keyBetween(String value1, String value2) {
            addCriterion("entity_key between", value1, value2, "entity_key");
            return (Criteria) this;
        }

        public Criteria andEntity_keyNotBetween(String value1, String value2) {
            addCriterion("entity_key not between", value1, value2, "entity_key");
            return (Criteria) this;
        }

        public Criteria andLang_typeIsNull() {
            addCriterion("lang_type is null");
            return (Criteria) this;
        }

        public Criteria andLang_typeIsNotNull() {
            addCriterion("lang_type is not null");
            return (Criteria) this;
        }

        public Criteria andLang_typeEqualTo(String value) {
            addCriterion("lang_type =", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeNotEqualTo(String value) {
            addCriterion("lang_type <>", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeGreaterThan(String value) {
            addCriterion("lang_type >", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeGreaterThanOrEqualTo(String value) {
            addCriterion("lang_type >=", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeLessThan(String value) {
            addCriterion("lang_type <", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeLessThanOrEqualTo(String value) {
            addCriterion("lang_type <=", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeLike(String value) {
            addCriterion("lang_type like", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeNotLike(String value) {
            addCriterion("lang_type not like", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeIn(List<String> values) {
            addCriterion("lang_type in", values, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeNotIn(List<String> values) {
            addCriterion("lang_type not in", values, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeBetween(String value1, String value2) {
            addCriterion("lang_type between", value1, value2, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeNotBetween(String value1, String value2) {
            addCriterion("lang_type not between", value1, value2, "lang_type");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entity
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entity
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}