package com.mwyq.model;

import java.util.ArrayList;
import java.util.List;

public class EntityTopicRelationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entity_topic_relation
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entity_topic_relation
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entity_topic_relation
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_topic_relation
     *
     * @mbggenerated
     */
    public EntityTopicRelationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_topic_relation
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_topic_relation
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_topic_relation
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_topic_relation
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_topic_relation
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_topic_relation
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_topic_relation
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_topic_relation
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_topic_relation
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_topic_relation
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entity_topic_relation
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEntity_idIsNull() {
            addCriterion("entity_id is null");
            return (Criteria) this;
        }

        public Criteria andEntity_idIsNotNull() {
            addCriterion("entity_id is not null");
            return (Criteria) this;
        }

        public Criteria andEntity_idEqualTo(Integer value) {
            addCriterion("entity_id =", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idNotEqualTo(Integer value) {
            addCriterion("entity_id <>", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idGreaterThan(Integer value) {
            addCriterion("entity_id >", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("entity_id >=", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idLessThan(Integer value) {
            addCriterion("entity_id <", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idLessThanOrEqualTo(Integer value) {
            addCriterion("entity_id <=", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idIn(List<Integer> values) {
            addCriterion("entity_id in", values, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idNotIn(List<Integer> values) {
            addCriterion("entity_id not in", values, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idBetween(Integer value1, Integer value2) {
            addCriterion("entity_id between", value1, value2, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idNotBetween(Integer value1, Integer value2) {
            addCriterion("entity_id not between", value1, value2, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_typeIsNull() {
            addCriterion("entity_type is null");
            return (Criteria) this;
        }

        public Criteria andEntity_typeIsNotNull() {
            addCriterion("entity_type is not null");
            return (Criteria) this;
        }

        public Criteria andEntity_typeEqualTo(String value) {
            addCriterion("entity_type =", value, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeNotEqualTo(String value) {
            addCriterion("entity_type <>", value, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeGreaterThan(String value) {
            addCriterion("entity_type >", value, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeGreaterThanOrEqualTo(String value) {
            addCriterion("entity_type >=", value, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeLessThan(String value) {
            addCriterion("entity_type <", value, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeLessThanOrEqualTo(String value) {
            addCriterion("entity_type <=", value, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeLike(String value) {
            addCriterion("entity_type like", value, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeNotLike(String value) {
            addCriterion("entity_type not like", value, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeIn(List<String> values) {
            addCriterion("entity_type in", values, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeNotIn(List<String> values) {
            addCriterion("entity_type not in", values, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeBetween(String value1, String value2) {
            addCriterion("entity_type between", value1, value2, "entity_type");
            return (Criteria) this;
        }

        public Criteria andEntity_typeNotBetween(String value1, String value2) {
            addCriterion("entity_type not between", value1, value2, "entity_type");
            return (Criteria) this;
        }

        public Criteria andTopic_idIsNull() {
            addCriterion("topic_id is null");
            return (Criteria) this;
        }

        public Criteria andTopic_idIsNotNull() {
            addCriterion("topic_id is not null");
            return (Criteria) this;
        }

        public Criteria andTopic_idEqualTo(String value) {
            addCriterion("topic_id =", value, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idNotEqualTo(String value) {
            addCriterion("topic_id <>", value, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idGreaterThan(String value) {
            addCriterion("topic_id >", value, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idGreaterThanOrEqualTo(String value) {
            addCriterion("topic_id >=", value, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idLessThan(String value) {
            addCriterion("topic_id <", value, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idLessThanOrEqualTo(String value) {
            addCriterion("topic_id <=", value, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idLike(String value) {
            addCriterion("topic_id like", value, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idNotLike(String value) {
            addCriterion("topic_id not like", value, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idIn(List<String> values) {
            addCriterion("topic_id in", values, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idNotIn(List<String> values) {
            addCriterion("topic_id not in", values, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idBetween(String value1, String value2) {
            addCriterion("topic_id between", value1, value2, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idNotBetween(String value1, String value2) {
            addCriterion("topic_id not between", value1, value2, "topic_id");
            return (Criteria) this;
        }

        public Criteria andRelationIsNull() {
            addCriterion("relation is null");
            return (Criteria) this;
        }

        public Criteria andRelationIsNotNull() {
            addCriterion("relation is not null");
            return (Criteria) this;
        }

        public Criteria andRelationEqualTo(Double value) {
            addCriterion("relation =", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationNotEqualTo(Double value) {
            addCriterion("relation <>", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationGreaterThan(Double value) {
            addCriterion("relation >", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationGreaterThanOrEqualTo(Double value) {
            addCriterion("relation >=", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationLessThan(Double value) {
            addCriterion("relation <", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationLessThanOrEqualTo(Double value) {
            addCriterion("relation <=", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationIn(List<Double> values) {
            addCriterion("relation in", values, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationNotIn(List<Double> values) {
            addCriterion("relation not in", values, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationBetween(Double value1, Double value2) {
            addCriterion("relation between", value1, value2, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationNotBetween(Double value1, Double value2) {
            addCriterion("relation not between", value1, value2, "relation");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entity_topic_relation
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entity_topic_relation
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}