package com.mwyq.model;

import java.util.Date;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_id
     *
     * @mbggenerated
     */
    private Integer news_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_token
     *
     * @mbggenerated
     */
    private String news_token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.words_num
     *
     * @mbggenerated
     */
    private Integer words_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.generated_keywords
     *
     * @mbggenerated
     */
    private String generated_keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_category
     *
     * @mbggenerated
     */
    private String news_category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_source
     *
     * @mbggenerated
     */
    private String news_source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_title
     *
     * @mbggenerated
     */
    private String news_title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title_token
     *
     * @mbggenerated
     */
    private String title_token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title_lading
     *
     * @mbggenerated
     */
    private String title_lading;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.inborn_keywords
     *
     * @mbggenerated
     */
    private String inborn_keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_time
     *
     * @mbggenerated
     */
    private Date news_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_url
     *
     * @mbggenerated
     */
    private String news_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_author
     *
     * @mbggenerated
     */
    private String news_author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_content
     *
     * @mbggenerated
     */
    private String news_content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content_lading
     *
     * @mbggenerated
     */
    private String content_lading;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.lang_type
     *
     * @mbggenerated
     */
    private String lang_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.crawl_source
     *
     * @mbggenerated
     */
    private String crawl_source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.crawl_time
     *
     * @mbggenerated
     */
    private Date crawl_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_pictures
     *
     * @mbggenerated
     */
    private String news_pictures;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_video
     *
     * @mbggenerated
     */
    private String news_video;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_encode
     *
     * @mbggenerated
     */
    private String news_encode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_tendency
     *
     * @mbggenerated
     */
    private String news_tendency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.is_seged
     *
     * @mbggenerated
     */
    private String is_seged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.update_time
     *
     * @mbggenerated
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.has_video
     *
     * @mbggenerated
     */
    private String has_video;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_id
     *
     * @return the value of news.news_id
     *
     * @mbggenerated
     */
    
    private String sensitive_words;
    
    private Integer is_sensitive;
    
    private String websitename;

   
    
    
    public Integer getNews_id() {
        return news_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_id
     *
     * @param news_id the value for news.news_id
     *
     * @mbggenerated
     */
    
    

    
    public void setNews_id(Integer news_id) {
        this.news_id = news_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_token
     *
     * @return the value of news.news_token
     *
     * @mbggenerated
     */
    public String getNews_token() {
        return news_token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_token
     *
     * @param news_token the value for news.news_token
     *
     * @mbggenerated
     */
    public void setNews_token(String news_token) {
        this.news_token = news_token == null ? null : news_token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.words_num
     *
     * @return the value of news.words_num
     *
     * @mbggenerated
     */
    public Integer getWords_num() {
        return words_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.words_num
     *
     * @param words_num the value for news.words_num
     *
     * @mbggenerated
     */
    public void setWords_num(Integer words_num) {
        this.words_num = words_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.generated_keywords
     *
     * @return the value of news.generated_keywords
     *
     * @mbggenerated
     */
    public String getGenerated_keywords() {
        return generated_keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.generated_keywords
     *
     * @param generated_keywords the value for news.generated_keywords
     *
     * @mbggenerated
     */
    public void setGenerated_keywords(String generated_keywords) {
        this.generated_keywords = generated_keywords == null ? null : generated_keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_category
     *
     * @return the value of news.news_category
     *
     * @mbggenerated
     */
    public String getNews_category() {
        return news_category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_category
     *
     * @param news_category the value for news.news_category
     *
     * @mbggenerated
     */
    public void setNews_category(String news_category) {
        this.news_category = news_category == null ? null : news_category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_source
     *
     * @return the value of news.news_source
     *
     * @mbggenerated
     */
    public String getNews_source() {
        return news_source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_source
     *
     * @param news_source the value for news.news_source
     *
     * @mbggenerated
     */
    public void setNews_source(String news_source) {
        this.news_source = news_source == null ? null : news_source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_title
     *
     * @return the value of news.news_title
     *
     * @mbggenerated
     */
    public String getNews_title() {
        return news_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_title
     *
     * @param news_title the value for news.news_title
     *
     * @mbggenerated
     */
    public void setNews_title(String news_title) {
        this.news_title = news_title == null ? null : news_title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title_token
     *
     * @return the value of news.title_token
     *
     * @mbggenerated
     */
    public String getTitle_token() {
        return title_token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title_token
     *
     * @param title_token the value for news.title_token
     *
     * @mbggenerated
     */
    public void setTitle_token(String title_token) {
        this.title_token = title_token == null ? null : title_token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title_lading
     *
     * @return the value of news.title_lading
     *
     * @mbggenerated
     */
    public String getTitle_lading() {
        return title_lading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title_lading
     *
     * @param title_lading the value for news.title_lading
     *
     * @mbggenerated
     */
    public void setTitle_lading(String title_lading) {
        this.title_lading = title_lading == null ? null : title_lading.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.inborn_keywords
     *
     * @return the value of news.inborn_keywords
     *
     * @mbggenerated
     */
    public String getInborn_keywords() {
        return inborn_keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.inborn_keywords
     *
     * @param inborn_keywords the value for news.inborn_keywords
     *
     * @mbggenerated
     */
    public void setInborn_keywords(String inborn_keywords) {
        this.inborn_keywords = inborn_keywords == null ? null : inborn_keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_time
     *
     * @return the value of news.news_time
     *
     * @mbggenerated
     */
    public Date getNews_time() {
        return news_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_time
     *
     * @param news_time the value for news.news_time
     *
     * @mbggenerated
     */
    public void setNews_time(Date news_time) {
        this.news_time = news_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_url
     *
     * @return the value of news.news_url
     *
     * @mbggenerated
     */
    public String getNews_url() {
        return news_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_url
     *
     * @param news_url the value for news.news_url
     *
     * @mbggenerated
     */
    public void setNews_url(String news_url) {
        this.news_url = news_url == null ? null : news_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_author
     *
     * @return the value of news.news_author
     *
     * @mbggenerated
     */
    public String getNews_author() {
        return news_author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_author
     *
     * @param news_author the value for news.news_author
     *
     * @mbggenerated
     */
    public void setNews_author(String news_author) {
        this.news_author = news_author == null ? null : news_author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_content
     *
     * @return the value of news.news_content
     *
     * @mbggenerated
     */
    public String getNews_content() {
        return news_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_content
     *
     * @param news_content the value for news.news_content
     *
     * @mbggenerated
     */
    public void setNews_content(String news_content) {
        this.news_content = news_content == null ? null : news_content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content_lading
     *
     * @return the value of news.content_lading
     *
     * @mbggenerated
     */
    public String getContent_lading() {
        return content_lading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content_lading
     *
     * @param content_lading the value for news.content_lading
     *
     * @mbggenerated
     */
    public void setContent_lading(String content_lading) {
        this.content_lading = content_lading == null ? null : content_lading.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.lang_type
     *
     * @return the value of news.lang_type
     *
     * @mbggenerated
     */
    public String getLang_type() {
        return lang_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.lang_type
     *
     * @param lang_type the value for news.lang_type
     *
     * @mbggenerated
     */
    public void setLang_type(String lang_type) {
        this.lang_type = lang_type == null ? null : lang_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.crawl_source
     *
     * @return the value of news.crawl_source
     *
     * @mbggenerated
     */
    public String getCrawl_source() {
        return crawl_source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.crawl_source
     *
     * @param crawl_source the value for news.crawl_source
     *
     * @mbggenerated
     */
    public void setCrawl_source(String crawl_source) {
        this.crawl_source = crawl_source == null ? null : crawl_source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.crawl_time
     *
     * @return the value of news.crawl_time
     *
     * @mbggenerated
     */
    public Date getCrawl_time() {
        return crawl_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.crawl_time
     *
     * @param crawl_time the value for news.crawl_time
     *
     * @mbggenerated
     */
    public void setCrawl_time(Date crawl_time) {
        this.crawl_time = crawl_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_pictures
     *
     * @return the value of news.news_pictures
     *
     * @mbggenerated
     */
    public String getNews_pictures() {
        return news_pictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_pictures
     *
     * @param news_pictures the value for news.news_pictures
     *
     * @mbggenerated
     */
    public void setNews_pictures(String news_pictures) {
        this.news_pictures = news_pictures == null ? null : news_pictures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_video
     *
     * @return the value of news.news_video
     *
     * @mbggenerated
     */
    public String getNews_video() {
        return news_video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_video
     *
     * @param news_video the value for news.news_video
     *
     * @mbggenerated
     */
    public void setNews_video(String news_video) {
        this.news_video = news_video == null ? null : news_video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_encode
     *
     * @return the value of news.news_encode
     *
     * @mbggenerated
     */
    public String getNews_encode() {
        return news_encode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_encode
     *
     * @param news_encode the value for news.news_encode
     *
     * @mbggenerated
     */
    public void setNews_encode(String news_encode) {
        this.news_encode = news_encode == null ? null : news_encode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_tendency
     *
     * @return the value of news.news_tendency
     *
     * @mbggenerated
     */
    public String getNews_tendency() {
        return news_tendency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_tendency
     *
     * @param news_tendency the value for news.news_tendency
     *
     * @mbggenerated
     */
    public void setNews_tendency(String news_tendency) {
        this.news_tendency = news_tendency == null ? null : news_tendency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.is_seged
     *
     * @return the value of news.is_seged
     *
     * @mbggenerated
     */
    public String getIs_seged() {
        return is_seged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.is_seged
     *
     * @param is_seged the value for news.is_seged
     *
     * @mbggenerated
     */
    public void setIs_seged(String is_seged) {
        this.is_seged = is_seged == null ? null : is_seged.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.update_time
     *
     * @return the value of news.update_time
     *
     * @mbggenerated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.update_time
     *
     * @param update_time the value for news.update_time
     *
     * @mbggenerated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.has_video
     *
     * @return the value of news.has_video
     *
     * @mbggenerated
     */
    public String getHas_video() {
        return has_video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.has_video
     *
     * @param has_video the value for news.has_video
     *
     * @mbggenerated
     */
    public void setHas_video(String has_video) {
        this.has_video = has_video == null ? null : has_video.trim();
    }

	public String getSensitive_words() {
		return sensitive_words;
	}

	public void setSensitive_words(String sensitive_words) {
		this.sensitive_words = sensitive_words;
	}

	public Integer getIs_sensitive() {
		return is_sensitive;
	}

	public void setIs_sensitive(Integer is_sensitive) {
		this.is_sensitive = is_sensitive;
	}

	public String getWebsitename() {
		return websitename;
	}

	public void setWebsitename(String websitename) {
		this.websitename = websitename;
	}
	
}