package com.mwyq.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NewsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    public NewsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNews_idIsNull() {
            addCriterion("news_id is null");
            return (Criteria) this;
        }

        public Criteria andNews_idIsNotNull() {
            addCriterion("news_id is not null");
            return (Criteria) this;
        }

        public Criteria andNews_idEqualTo(Integer value) {
            addCriterion("news_id =", value, "news_id");
            return (Criteria) this;
        }

        public Criteria andNews_idNotEqualTo(Integer value) {
            addCriterion("news_id <>", value, "news_id");
            return (Criteria) this;
        }

        public Criteria andNews_idGreaterThan(Integer value) {
            addCriterion("news_id >", value, "news_id");
            return (Criteria) this;
        }

        public Criteria andNews_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("news_id >=", value, "news_id");
            return (Criteria) this;
        }

        public Criteria andNews_idLessThan(Integer value) {
            addCriterion("news_id <", value, "news_id");
            return (Criteria) this;
        }

        public Criteria andNews_idLessThanOrEqualTo(Integer value) {
            addCriterion("news_id <=", value, "news_id");
            return (Criteria) this;
        }

        public Criteria andNews_idIn(List<Integer> values) {
            addCriterion("news_id in", values, "news_id");
            return (Criteria) this;
        }

        public Criteria andNews_idNotIn(List<Integer> values) {
            addCriterion("news_id not in", values, "news_id");
            return (Criteria) this;
        }

        public Criteria andNews_idBetween(Integer value1, Integer value2) {
            addCriterion("news_id between", value1, value2, "news_id");
            return (Criteria) this;
        }

        public Criteria andNews_idNotBetween(Integer value1, Integer value2) {
            addCriterion("news_id not between", value1, value2, "news_id");
            return (Criteria) this;
        }

        public Criteria andNews_tokenIsNull() {
            addCriterion("news_token is null");
            return (Criteria) this;
        }

        public Criteria andNews_tokenIsNotNull() {
            addCriterion("news_token is not null");
            return (Criteria) this;
        }

        public Criteria andNews_tokenEqualTo(String value) {
            addCriterion("news_token =", value, "news_token");
            return (Criteria) this;
        }

        public Criteria andNews_tokenNotEqualTo(String value) {
            addCriterion("news_token <>", value, "news_token");
            return (Criteria) this;
        }

        public Criteria andNews_tokenGreaterThan(String value) {
            addCriterion("news_token >", value, "news_token");
            return (Criteria) this;
        }

        public Criteria andNews_tokenGreaterThanOrEqualTo(String value) {
            addCriterion("news_token >=", value, "news_token");
            return (Criteria) this;
        }

        public Criteria andNews_tokenLessThan(String value) {
            addCriterion("news_token <", value, "news_token");
            return (Criteria) this;
        }

        public Criteria andNews_tokenLessThanOrEqualTo(String value) {
            addCriterion("news_token <=", value, "news_token");
            return (Criteria) this;
        }

        public Criteria andNews_tokenLike(String value) {
            addCriterion("news_token like", value, "news_token");
            return (Criteria) this;
        }

        public Criteria andNews_tokenNotLike(String value) {
            addCriterion("news_token not like", value, "news_token");
            return (Criteria) this;
        }

        public Criteria andNews_tokenIn(List<String> values) {
            addCriterion("news_token in", values, "news_token");
            return (Criteria) this;
        }

        public Criteria andNews_tokenNotIn(List<String> values) {
            addCriterion("news_token not in", values, "news_token");
            return (Criteria) this;
        }

        public Criteria andNews_tokenBetween(String value1, String value2) {
            addCriterion("news_token between", value1, value2, "news_token");
            return (Criteria) this;
        }

        public Criteria andNews_tokenNotBetween(String value1, String value2) {
            addCriterion("news_token not between", value1, value2, "news_token");
            return (Criteria) this;
        }

        public Criteria andWords_numIsNull() {
            addCriterion("words_num is null");
            return (Criteria) this;
        }

        public Criteria andWords_numIsNotNull() {
            addCriterion("words_num is not null");
            return (Criteria) this;
        }

        public Criteria andWords_numEqualTo(Integer value) {
            addCriterion("words_num =", value, "words_num");
            return (Criteria) this;
        }

        public Criteria andWords_numNotEqualTo(Integer value) {
            addCriterion("words_num <>", value, "words_num");
            return (Criteria) this;
        }

        public Criteria andWords_numGreaterThan(Integer value) {
            addCriterion("words_num >", value, "words_num");
            return (Criteria) this;
        }

        public Criteria andWords_numGreaterThanOrEqualTo(Integer value) {
            addCriterion("words_num >=", value, "words_num");
            return (Criteria) this;
        }

        public Criteria andWords_numLessThan(Integer value) {
            addCriterion("words_num <", value, "words_num");
            return (Criteria) this;
        }

        public Criteria andWords_numLessThanOrEqualTo(Integer value) {
            addCriterion("words_num <=", value, "words_num");
            return (Criteria) this;
        }

        public Criteria andWords_numIn(List<Integer> values) {
            addCriterion("words_num in", values, "words_num");
            return (Criteria) this;
        }

        public Criteria andWords_numNotIn(List<Integer> values) {
            addCriterion("words_num not in", values, "words_num");
            return (Criteria) this;
        }

        public Criteria andWords_numBetween(Integer value1, Integer value2) {
            addCriterion("words_num between", value1, value2, "words_num");
            return (Criteria) this;
        }

        public Criteria andWords_numNotBetween(Integer value1, Integer value2) {
            addCriterion("words_num not between", value1, value2, "words_num");
            return (Criteria) this;
        }

        public Criteria andGenerated_keywordsIsNull() {
            addCriterion("generated_keywords is null");
            return (Criteria) this;
        }

        public Criteria andGenerated_keywordsIsNotNull() {
            addCriterion("generated_keywords is not null");
            return (Criteria) this;
        }

        public Criteria andGenerated_keywordsEqualTo(String value) {
            addCriterion("generated_keywords =", value, "generated_keywords");
            return (Criteria) this;
        }

        public Criteria andGenerated_keywordsNotEqualTo(String value) {
            addCriterion("generated_keywords <>", value, "generated_keywords");
            return (Criteria) this;
        }

        public Criteria andGenerated_keywordsGreaterThan(String value) {
            addCriterion("generated_keywords >", value, "generated_keywords");
            return (Criteria) this;
        }

        public Criteria andGenerated_keywordsGreaterThanOrEqualTo(String value) {
            addCriterion("generated_keywords >=", value, "generated_keywords");
            return (Criteria) this;
        }

        public Criteria andGenerated_keywordsLessThan(String value) {
            addCriterion("generated_keywords <", value, "generated_keywords");
            return (Criteria) this;
        }

        public Criteria andGenerated_keywordsLessThanOrEqualTo(String value) {
            addCriterion("generated_keywords <=", value, "generated_keywords");
            return (Criteria) this;
        }

        public Criteria andGenerated_keywordsLike(String value) {
            addCriterion("generated_keywords like", value, "generated_keywords");
            return (Criteria) this;
        }

        public Criteria andGenerated_keywordsNotLike(String value) {
            addCriterion("generated_keywords not like", value, "generated_keywords");
            return (Criteria) this;
        }

        public Criteria andGenerated_keywordsIn(List<String> values) {
            addCriterion("generated_keywords in", values, "generated_keywords");
            return (Criteria) this;
        }

        public Criteria andGenerated_keywordsNotIn(List<String> values) {
            addCriterion("generated_keywords not in", values, "generated_keywords");
            return (Criteria) this;
        }

        public Criteria andGenerated_keywordsBetween(String value1, String value2) {
            addCriterion("generated_keywords between", value1, value2, "generated_keywords");
            return (Criteria) this;
        }

        public Criteria andGenerated_keywordsNotBetween(String value1, String value2) {
            addCriterion("generated_keywords not between", value1, value2, "generated_keywords");
            return (Criteria) this;
        }

        public Criteria andNews_categoryIsNull() {
            addCriterion("news_category is null");
            return (Criteria) this;
        }

        public Criteria andNews_categoryIsNotNull() {
            addCriterion("news_category is not null");
            return (Criteria) this;
        }

        public Criteria andNews_categoryEqualTo(String value) {
            addCriterion("news_category =", value, "news_category");
            return (Criteria) this;
        }

        public Criteria andNews_categoryNotEqualTo(String value) {
            addCriterion("news_category <>", value, "news_category");
            return (Criteria) this;
        }

        public Criteria andNews_categoryGreaterThan(String value) {
            addCriterion("news_category >", value, "news_category");
            return (Criteria) this;
        }

        public Criteria andNews_categoryGreaterThanOrEqualTo(String value) {
            addCriterion("news_category >=", value, "news_category");
            return (Criteria) this;
        }

        public Criteria andNews_categoryLessThan(String value) {
            addCriterion("news_category <", value, "news_category");
            return (Criteria) this;
        }

        public Criteria andNews_categoryLessThanOrEqualTo(String value) {
            addCriterion("news_category <=", value, "news_category");
            return (Criteria) this;
        }

        public Criteria andNews_categoryLike(String value) {
            addCriterion("news_category like", value, "news_category");
            return (Criteria) this;
        }

        public Criteria andNews_categoryNotLike(String value) {
            addCriterion("news_category not like", value, "news_category");
            return (Criteria) this;
        }

        public Criteria andNews_categoryIn(List<String> values) {
            addCriterion("news_category in", values, "news_category");
            return (Criteria) this;
        }

        public Criteria andNews_categoryNotIn(List<String> values) {
            addCriterion("news_category not in", values, "news_category");
            return (Criteria) this;
        }

        public Criteria andNews_categoryBetween(String value1, String value2) {
            addCriterion("news_category between", value1, value2, "news_category");
            return (Criteria) this;
        }

        public Criteria andNews_categoryNotBetween(String value1, String value2) {
            addCriterion("news_category not between", value1, value2, "news_category");
            return (Criteria) this;
        }

        public Criteria andNews_sourceIsNull() {
            addCriterion("news_source is null");
            return (Criteria) this;
        }

        public Criteria andNews_sourceIsNotNull() {
            addCriterion("news_source is not null");
            return (Criteria) this;
        }

        public Criteria andNews_sourceEqualTo(String value) {
            addCriterion("news_source =", value, "news_source");
            return (Criteria) this;
        }

        public Criteria andNews_sourceNotEqualTo(String value) {
            addCriterion("news_source <>", value, "news_source");
            return (Criteria) this;
        }

        public Criteria andNews_sourceGreaterThan(String value) {
            addCriterion("news_source >", value, "news_source");
            return (Criteria) this;
        }

        public Criteria andNews_sourceGreaterThanOrEqualTo(String value) {
            addCriterion("news_source >=", value, "news_source");
            return (Criteria) this;
        }

        public Criteria andNews_sourceLessThan(String value) {
            addCriterion("news_source <", value, "news_source");
            return (Criteria) this;
        }

        public Criteria andNews_sourceLessThanOrEqualTo(String value) {
            addCriterion("news_source <=", value, "news_source");
            return (Criteria) this;
        }

        public Criteria andNews_sourceLike(String value) {
            addCriterion("news_source like", value, "news_source");
            return (Criteria) this;
        }

        public Criteria andNews_sourceNotLike(String value) {
            addCriterion("news_source not like", value, "news_source");
            return (Criteria) this;
        }

        public Criteria andNews_sourceIn(List<String> values) {
            addCriterion("news_source in", values, "news_source");
            return (Criteria) this;
        }

        public Criteria andNews_sourceNotIn(List<String> values) {
            addCriterion("news_source not in", values, "news_source");
            return (Criteria) this;
        }

        public Criteria andNews_sourceBetween(String value1, String value2) {
            addCriterion("news_source between", value1, value2, "news_source");
            return (Criteria) this;
        }

        public Criteria andNews_sourceNotBetween(String value1, String value2) {
            addCriterion("news_source not between", value1, value2, "news_source");
            return (Criteria) this;
        }

        public Criteria andNews_titleIsNull() {
            addCriterion("news_title is null");
            return (Criteria) this;
        }

        public Criteria andNews_titleIsNotNull() {
            addCriterion("news_title is not null");
            return (Criteria) this;
        }

        public Criteria andNews_titleEqualTo(String value) {
            addCriterion("news_title =", value, "news_title");
            return (Criteria) this;
        }

        public Criteria andNews_titleNotEqualTo(String value) {
            addCriterion("news_title <>", value, "news_title");
            return (Criteria) this;
        }

        public Criteria andNews_titleGreaterThan(String value) {
            addCriterion("news_title >", value, "news_title");
            return (Criteria) this;
        }

        public Criteria andNews_titleGreaterThanOrEqualTo(String value) {
            addCriterion("news_title >=", value, "news_title");
            return (Criteria) this;
        }

        public Criteria andNews_titleLessThan(String value) {
            addCriterion("news_title <", value, "news_title");
            return (Criteria) this;
        }

        public Criteria andNews_titleLessThanOrEqualTo(String value) {
            addCriterion("news_title <=", value, "news_title");
            return (Criteria) this;
        }

        public Criteria andNews_titleLike(String value) {
            addCriterion("news_title like", value, "news_title");
            return (Criteria) this;
        }

        public Criteria andNews_titleNotLike(String value) {
            addCriterion("news_title not like", value, "news_title");
            return (Criteria) this;
        }

        public Criteria andNews_titleIn(List<String> values) {
            addCriterion("news_title in", values, "news_title");
            return (Criteria) this;
        }

        public Criteria andNews_titleNotIn(List<String> values) {
            addCriterion("news_title not in", values, "news_title");
            return (Criteria) this;
        }

        public Criteria andNews_titleBetween(String value1, String value2) {
            addCriterion("news_title between", value1, value2, "news_title");
            return (Criteria) this;
        }

        public Criteria andNews_titleNotBetween(String value1, String value2) {
            addCriterion("news_title not between", value1, value2, "news_title");
            return (Criteria) this;
        }

        public Criteria andTitle_tokenIsNull() {
            addCriterion("title_token is null");
            return (Criteria) this;
        }

        public Criteria andTitle_tokenIsNotNull() {
            addCriterion("title_token is not null");
            return (Criteria) this;
        }

        public Criteria andTitle_tokenEqualTo(String value) {
            addCriterion("title_token =", value, "title_token");
            return (Criteria) this;
        }

        public Criteria andTitle_tokenNotEqualTo(String value) {
            addCriterion("title_token <>", value, "title_token");
            return (Criteria) this;
        }

        public Criteria andTitle_tokenGreaterThan(String value) {
            addCriterion("title_token >", value, "title_token");
            return (Criteria) this;
        }

        public Criteria andTitle_tokenGreaterThanOrEqualTo(String value) {
            addCriterion("title_token >=", value, "title_token");
            return (Criteria) this;
        }

        public Criteria andTitle_tokenLessThan(String value) {
            addCriterion("title_token <", value, "title_token");
            return (Criteria) this;
        }

        public Criteria andTitle_tokenLessThanOrEqualTo(String value) {
            addCriterion("title_token <=", value, "title_token");
            return (Criteria) this;
        }

        public Criteria andTitle_tokenLike(String value) {
            addCriterion("title_token like", value, "title_token");
            return (Criteria) this;
        }

        public Criteria andTitle_tokenNotLike(String value) {
            addCriterion("title_token not like", value, "title_token");
            return (Criteria) this;
        }

        public Criteria andTitle_tokenIn(List<String> values) {
            addCriterion("title_token in", values, "title_token");
            return (Criteria) this;
        }

        public Criteria andTitle_tokenNotIn(List<String> values) {
            addCriterion("title_token not in", values, "title_token");
            return (Criteria) this;
        }

        public Criteria andTitle_tokenBetween(String value1, String value2) {
            addCriterion("title_token between", value1, value2, "title_token");
            return (Criteria) this;
        }

        public Criteria andTitle_tokenNotBetween(String value1, String value2) {
            addCriterion("title_token not between", value1, value2, "title_token");
            return (Criteria) this;
        }

        public Criteria andTitle_ladingIsNull() {
            addCriterion("title_lading is null");
            return (Criteria) this;
        }

        public Criteria andTitle_ladingIsNotNull() {
            addCriterion("title_lading is not null");
            return (Criteria) this;
        }

        public Criteria andTitle_ladingEqualTo(String value) {
            addCriterion("title_lading =", value, "title_lading");
            return (Criteria) this;
        }

        public Criteria andTitle_ladingNotEqualTo(String value) {
            addCriterion("title_lading <>", value, "title_lading");
            return (Criteria) this;
        }

        public Criteria andTitle_ladingGreaterThan(String value) {
            addCriterion("title_lading >", value, "title_lading");
            return (Criteria) this;
        }

        public Criteria andTitle_ladingGreaterThanOrEqualTo(String value) {
            addCriterion("title_lading >=", value, "title_lading");
            return (Criteria) this;
        }

        public Criteria andTitle_ladingLessThan(String value) {
            addCriterion("title_lading <", value, "title_lading");
            return (Criteria) this;
        }

        public Criteria andTitle_ladingLessThanOrEqualTo(String value) {
            addCriterion("title_lading <=", value, "title_lading");
            return (Criteria) this;
        }

        public Criteria andTitle_ladingLike(String value) {
            addCriterion("title_lading like", value, "title_lading");
            return (Criteria) this;
        }

        public Criteria andTitle_ladingNotLike(String value) {
            addCriterion("title_lading not like", value, "title_lading");
            return (Criteria) this;
        }

        public Criteria andTitle_ladingIn(List<String> values) {
            addCriterion("title_lading in", values, "title_lading");
            return (Criteria) this;
        }

        public Criteria andTitle_ladingNotIn(List<String> values) {
            addCriterion("title_lading not in", values, "title_lading");
            return (Criteria) this;
        }

        public Criteria andTitle_ladingBetween(String value1, String value2) {
            addCriterion("title_lading between", value1, value2, "title_lading");
            return (Criteria) this;
        }

        public Criteria andTitle_ladingNotBetween(String value1, String value2) {
            addCriterion("title_lading not between", value1, value2, "title_lading");
            return (Criteria) this;
        }

        public Criteria andInborn_keywordsIsNull() {
            addCriterion("inborn_keywords is null");
            return (Criteria) this;
        }

        public Criteria andInborn_keywordsIsNotNull() {
            addCriterion("inborn_keywords is not null");
            return (Criteria) this;
        }

        public Criteria andInborn_keywordsEqualTo(String value) {
            addCriterion("inborn_keywords =", value, "inborn_keywords");
            return (Criteria) this;
        }

        public Criteria andInborn_keywordsNotEqualTo(String value) {
            addCriterion("inborn_keywords <>", value, "inborn_keywords");
            return (Criteria) this;
        }

        public Criteria andInborn_keywordsGreaterThan(String value) {
            addCriterion("inborn_keywords >", value, "inborn_keywords");
            return (Criteria) this;
        }

        public Criteria andInborn_keywordsGreaterThanOrEqualTo(String value) {
            addCriterion("inborn_keywords >=", value, "inborn_keywords");
            return (Criteria) this;
        }

        public Criteria andInborn_keywordsLessThan(String value) {
            addCriterion("inborn_keywords <", value, "inborn_keywords");
            return (Criteria) this;
        }

        public Criteria andInborn_keywordsLessThanOrEqualTo(String value) {
            addCriterion("inborn_keywords <=", value, "inborn_keywords");
            return (Criteria) this;
        }

        public Criteria andInborn_keywordsLike(String value) {
            addCriterion("inborn_keywords like", value, "inborn_keywords");
            return (Criteria) this;
        }

        public Criteria andInborn_keywordsNotLike(String value) {
            addCriterion("inborn_keywords not like", value, "inborn_keywords");
            return (Criteria) this;
        }

        public Criteria andInborn_keywordsIn(List<String> values) {
            addCriterion("inborn_keywords in", values, "inborn_keywords");
            return (Criteria) this;
        }

        public Criteria andInborn_keywordsNotIn(List<String> values) {
            addCriterion("inborn_keywords not in", values, "inborn_keywords");
            return (Criteria) this;
        }

        public Criteria andInborn_keywordsBetween(String value1, String value2) {
            addCriterion("inborn_keywords between", value1, value2, "inborn_keywords");
            return (Criteria) this;
        }

        public Criteria andInborn_keywordsNotBetween(String value1, String value2) {
            addCriterion("inborn_keywords not between", value1, value2, "inborn_keywords");
            return (Criteria) this;
        }

        public Criteria andNews_timeIsNull() {
            addCriterion("news_time is null");
            return (Criteria) this;
        }

        public Criteria andNews_timeIsNotNull() {
            addCriterion("news_time is not null");
            return (Criteria) this;
        }

        public Criteria andNews_timeEqualTo(Date value) {
            addCriterion("news_time =", value, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeNotEqualTo(Date value) {
            addCriterion("news_time <>", value, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeGreaterThan(Date value) {
            addCriterion("news_time >", value, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("news_time >=", value, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeLessThan(Date value) {
            addCriterion("news_time <", value, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeLessThanOrEqualTo(Date value) {
            addCriterion("news_time <=", value, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeIn(List<Date> values) {
            addCriterion("news_time in", values, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeNotIn(List<Date> values) {
            addCriterion("news_time not in", values, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeBetween(Date value1, Date value2) {
            addCriterion("news_time between", value1, value2, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeNotBetween(Date value1, Date value2) {
            addCriterion("news_time not between", value1, value2, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_urlIsNull() {
            addCriterion("news_url is null");
            return (Criteria) this;
        }

        public Criteria andNews_urlIsNotNull() {
            addCriterion("news_url is not null");
            return (Criteria) this;
        }

        public Criteria andNews_urlEqualTo(String value) {
            addCriterion("news_url =", value, "news_url");
            return (Criteria) this;
        }

        public Criteria andNews_urlNotEqualTo(String value) {
            addCriterion("news_url <>", value, "news_url");
            return (Criteria) this;
        }

        public Criteria andNews_urlGreaterThan(String value) {
            addCriterion("news_url >", value, "news_url");
            return (Criteria) this;
        }

        public Criteria andNews_urlGreaterThanOrEqualTo(String value) {
            addCriterion("news_url >=", value, "news_url");
            return (Criteria) this;
        }

        public Criteria andNews_urlLessThan(String value) {
            addCriterion("news_url <", value, "news_url");
            return (Criteria) this;
        }

        public Criteria andNews_urlLessThanOrEqualTo(String value) {
            addCriterion("news_url <=", value, "news_url");
            return (Criteria) this;
        }

        public Criteria andNews_urlLike(String value) {
            addCriterion("news_url like", value, "news_url");
            return (Criteria) this;
        }

        public Criteria andNews_urlNotLike(String value) {
            addCriterion("news_url not like", value, "news_url");
            return (Criteria) this;
        }

        public Criteria andNews_urlIn(List<String> values) {
            addCriterion("news_url in", values, "news_url");
            return (Criteria) this;
        }

        public Criteria andNews_urlNotIn(List<String> values) {
            addCriterion("news_url not in", values, "news_url");
            return (Criteria) this;
        }

        public Criteria andNews_urlBetween(String value1, String value2) {
            addCriterion("news_url between", value1, value2, "news_url");
            return (Criteria) this;
        }

        public Criteria andNews_urlNotBetween(String value1, String value2) {
            addCriterion("news_url not between", value1, value2, "news_url");
            return (Criteria) this;
        }

        public Criteria andNews_authorIsNull() {
            addCriterion("news_author is null");
            return (Criteria) this;
        }

        public Criteria andNews_authorIsNotNull() {
            addCriterion("news_author is not null");
            return (Criteria) this;
        }

        public Criteria andNews_authorEqualTo(String value) {
            addCriterion("news_author =", value, "news_author");
            return (Criteria) this;
        }

        public Criteria andNews_authorNotEqualTo(String value) {
            addCriterion("news_author <>", value, "news_author");
            return (Criteria) this;
        }

        public Criteria andNews_authorGreaterThan(String value) {
            addCriterion("news_author >", value, "news_author");
            return (Criteria) this;
        }

        public Criteria andNews_authorGreaterThanOrEqualTo(String value) {
            addCriterion("news_author >=", value, "news_author");
            return (Criteria) this;
        }

        public Criteria andNews_authorLessThan(String value) {
            addCriterion("news_author <", value, "news_author");
            return (Criteria) this;
        }

        public Criteria andNews_authorLessThanOrEqualTo(String value) {
            addCriterion("news_author <=", value, "news_author");
            return (Criteria) this;
        }

        public Criteria andNews_authorLike(String value) {
            addCriterion("news_author like", value, "news_author");
            return (Criteria) this;
        }

        public Criteria andNews_authorNotLike(String value) {
            addCriterion("news_author not like", value, "news_author");
            return (Criteria) this;
        }

        public Criteria andNews_authorIn(List<String> values) {
            addCriterion("news_author in", values, "news_author");
            return (Criteria) this;
        }

        public Criteria andNews_authorNotIn(List<String> values) {
            addCriterion("news_author not in", values, "news_author");
            return (Criteria) this;
        }

        public Criteria andNews_authorBetween(String value1, String value2) {
            addCriterion("news_author between", value1, value2, "news_author");
            return (Criteria) this;
        }

        public Criteria andNews_authorNotBetween(String value1, String value2) {
            addCriterion("news_author not between", value1, value2, "news_author");
            return (Criteria) this;
        }

        public Criteria andNews_contentIsNull() {
            addCriterion("news_content is null");
            return (Criteria) this;
        }

        public Criteria andNews_contentIsNotNull() {
            addCriterion("news_content is not null");
            return (Criteria) this;
        }

        public Criteria andNews_contentEqualTo(String value) {
            addCriterion("news_content =", value, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentNotEqualTo(String value) {
            addCriterion("news_content <>", value, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentGreaterThan(String value) {
            addCriterion("news_content >", value, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentGreaterThanOrEqualTo(String value) {
            addCriterion("news_content >=", value, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentLessThan(String value) {
            addCriterion("news_content <", value, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentLessThanOrEqualTo(String value) {
            addCriterion("news_content <=", value, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentLike(String value) {
            addCriterion("news_content like", value, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentNotLike(String value) {
            addCriterion("news_content not like", value, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentIn(List<String> values) {
            addCriterion("news_content in", values, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentNotIn(List<String> values) {
            addCriterion("news_content not in", values, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentBetween(String value1, String value2) {
            addCriterion("news_content between", value1, value2, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentNotBetween(String value1, String value2) {
            addCriterion("news_content not between", value1, value2, "news_content");
            return (Criteria) this;
        }

        public Criteria andContent_ladingIsNull() {
            addCriterion("content_lading is null");
            return (Criteria) this;
        }

        public Criteria andContent_ladingIsNotNull() {
            addCriterion("content_lading is not null");
            return (Criteria) this;
        }

        public Criteria andContent_ladingEqualTo(String value) {
            addCriterion("content_lading =", value, "content_lading");
            return (Criteria) this;
        }

        public Criteria andContent_ladingNotEqualTo(String value) {
            addCriterion("content_lading <>", value, "content_lading");
            return (Criteria) this;
        }

        public Criteria andContent_ladingGreaterThan(String value) {
            addCriterion("content_lading >", value, "content_lading");
            return (Criteria) this;
        }

        public Criteria andContent_ladingGreaterThanOrEqualTo(String value) {
            addCriterion("content_lading >=", value, "content_lading");
            return (Criteria) this;
        }

        public Criteria andContent_ladingLessThan(String value) {
            addCriterion("content_lading <", value, "content_lading");
            return (Criteria) this;
        }

        public Criteria andContent_ladingLessThanOrEqualTo(String value) {
            addCriterion("content_lading <=", value, "content_lading");
            return (Criteria) this;
        }

        public Criteria andContent_ladingLike(String value) {
            addCriterion("content_lading like", value, "content_lading");
            return (Criteria) this;
        }

        public Criteria andContent_ladingNotLike(String value) {
            addCriterion("content_lading not like", value, "content_lading");
            return (Criteria) this;
        }

        public Criteria andContent_ladingIn(List<String> values) {
            addCriterion("content_lading in", values, "content_lading");
            return (Criteria) this;
        }

        public Criteria andContent_ladingNotIn(List<String> values) {
            addCriterion("content_lading not in", values, "content_lading");
            return (Criteria) this;
        }

        public Criteria andContent_ladingBetween(String value1, String value2) {
            addCriterion("content_lading between", value1, value2, "content_lading");
            return (Criteria) this;
        }

        public Criteria andContent_ladingNotBetween(String value1, String value2) {
            addCriterion("content_lading not between", value1, value2, "content_lading");
            return (Criteria) this;
        }

        public Criteria andLang_typeIsNull() {
            addCriterion("lang_type is null");
            return (Criteria) this;
        }

        public Criteria andLang_typeIsNotNull() {
            addCriterion("lang_type is not null");
            return (Criteria) this;
        }

        public Criteria andLang_typeEqualTo(String value) {
            addCriterion("lang_type =", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeNotEqualTo(String value) {
            addCriterion("lang_type <>", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeGreaterThan(String value) {
            addCriterion("lang_type >", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeGreaterThanOrEqualTo(String value) {
            addCriterion("lang_type >=", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeLessThan(String value) {
            addCriterion("lang_type <", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeLessThanOrEqualTo(String value) {
            addCriterion("lang_type <=", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeLike(String value) {
            addCriterion("lang_type like", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeNotLike(String value) {
            addCriterion("lang_type not like", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeIn(List<String> values) {
            addCriterion("lang_type in", values, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeNotIn(List<String> values) {
            addCriterion("lang_type not in", values, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeBetween(String value1, String value2) {
            addCriterion("lang_type between", value1, value2, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeNotBetween(String value1, String value2) {
            addCriterion("lang_type not between", value1, value2, "lang_type");
            return (Criteria) this;
        }
        
        public Criteria andIs_sensitiveEqualTo(Integer value) {
            addCriterion("is_sensitive =", value, "is_sensitive");
            return (Criteria) this;
        }

        public Criteria andCrawl_sourceIsNull() {
            addCriterion("crawl_source is null");
            return (Criteria) this;
        }

        public Criteria andCrawl_sourceIsNotNull() {
            addCriterion("crawl_source is not null");
            return (Criteria) this;
        }

        public Criteria andCrawl_sourceEqualTo(String value) {
            addCriterion("crawl_source =", value, "crawl_source");
            return (Criteria) this;
        }

        public Criteria andCrawl_sourceNotEqualTo(String value) {
            addCriterion("crawl_source <>", value, "crawl_source");
            return (Criteria) this;
        }

        public Criteria andCrawl_sourceGreaterThan(String value) {
            addCriterion("crawl_source >", value, "crawl_source");
            return (Criteria) this;
        }

        public Criteria andCrawl_sourceGreaterThanOrEqualTo(String value) {
            addCriterion("crawl_source >=", value, "crawl_source");
            return (Criteria) this;
        }

        public Criteria andCrawl_sourceLessThan(String value) {
            addCriterion("crawl_source <", value, "crawl_source");
            return (Criteria) this;
        }

        public Criteria andCrawl_sourceLessThanOrEqualTo(String value) {
            addCriterion("crawl_source <=", value, "crawl_source");
            return (Criteria) this;
        }

        public Criteria andCrawl_sourceLike(String value) {
            addCriterion("crawl_source like", value, "crawl_source");
            return (Criteria) this;
        }

        public Criteria andCrawl_sourceNotLike(String value) {
            addCriterion("crawl_source not like", value, "crawl_source");
            return (Criteria) this;
        }

        public Criteria andCrawl_sourceIn(List<String> values) {
            addCriterion("crawl_source in", values, "crawl_source");
            return (Criteria) this;
        }

        public Criteria andCrawl_sourceNotIn(List<String> values) {
            addCriterion("crawl_source not in", values, "crawl_source");
            return (Criteria) this;
        }

        public Criteria andCrawl_sourceBetween(String value1, String value2) {
            addCriterion("crawl_source between", value1, value2, "crawl_source");
            return (Criteria) this;
        }

        public Criteria andCrawl_sourceNotBetween(String value1, String value2) {
            addCriterion("crawl_source not between", value1, value2, "crawl_source");
            return (Criteria) this;
        }

        public Criteria andCrawl_timeIsNull() {
            addCriterion("crawl_time is null");
            return (Criteria) this;
        }

        public Criteria andCrawl_timeIsNotNull() {
            addCriterion("crawl_time is not null");
            return (Criteria) this;
        }

        public Criteria andCrawl_timeEqualTo(Date value) {
            addCriterion("crawl_time =", value, "crawl_time");
            return (Criteria) this;
        }

        public Criteria andCrawl_timeNotEqualTo(Date value) {
            addCriterion("crawl_time <>", value, "crawl_time");
            return (Criteria) this;
        }

        public Criteria andCrawl_timeGreaterThan(Date value) {
            addCriterion("crawl_time >", value, "crawl_time");
            return (Criteria) this;
        }

        public Criteria andCrawl_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("crawl_time >=", value, "crawl_time");
            return (Criteria) this;
        }

        public Criteria andCrawl_timeLessThan(Date value) {
            addCriterion("crawl_time <", value, "crawl_time");
            return (Criteria) this;
        }

        public Criteria andCrawl_timeLessThanOrEqualTo(Date value) {
            addCriterion("crawl_time <=", value, "crawl_time");
            return (Criteria) this;
        }

        public Criteria andCrawl_timeIn(List<Date> values) {
            addCriterion("crawl_time in", values, "crawl_time");
            return (Criteria) this;
        }

        public Criteria andCrawl_timeNotIn(List<Date> values) {
            addCriterion("crawl_time not in", values, "crawl_time");
            return (Criteria) this;
        }

        public Criteria andCrawl_timeBetween(Date value1, Date value2) {
            addCriterion("crawl_time between", value1, value2, "crawl_time");
            return (Criteria) this;
        }

        public Criteria andCrawl_timeNotBetween(Date value1, Date value2) {
            addCriterion("crawl_time not between", value1, value2, "crawl_time");
            return (Criteria) this;
        }

        public Criteria andNews_picturesIsNull() {
            addCriterion("news_pictures is null");
            return (Criteria) this;
        }

        public Criteria andNews_picturesIsNotNull() {
            addCriterion("news_pictures is not null");
            return (Criteria) this;
        }

        public Criteria andNews_picturesEqualTo(String value) {
            addCriterion("news_pictures =", value, "news_pictures");
            return (Criteria) this;
        }

        public Criteria andNews_picturesNotEqualTo(String value) {
            addCriterion("news_pictures <>", value, "news_pictures");
            return (Criteria) this;
        }

        public Criteria andNews_picturesGreaterThan(String value) {
            addCriterion("news_pictures >", value, "news_pictures");
            return (Criteria) this;
        }

        public Criteria andNews_picturesGreaterThanOrEqualTo(String value) {
            addCriterion("news_pictures >=", value, "news_pictures");
            return (Criteria) this;
        }

        public Criteria andNews_picturesLessThan(String value) {
            addCriterion("news_pictures <", value, "news_pictures");
            return (Criteria) this;
        }

        public Criteria andNews_picturesLessThanOrEqualTo(String value) {
            addCriterion("news_pictures <=", value, "news_pictures");
            return (Criteria) this;
        }

        public Criteria andNews_picturesLike(String value) {
            addCriterion("news_pictures like", value, "news_pictures");
            return (Criteria) this;
        }

        public Criteria andNews_picturesNotLike(String value) {
            addCriterion("news_pictures not like", value, "news_pictures");
            return (Criteria) this;
        }

        public Criteria andNews_picturesIn(List<String> values) {
            addCriterion("news_pictures in", values, "news_pictures");
            return (Criteria) this;
        }

        public Criteria andNews_picturesNotIn(List<String> values) {
            addCriterion("news_pictures not in", values, "news_pictures");
            return (Criteria) this;
        }

        public Criteria andNews_picturesBetween(String value1, String value2) {
            addCriterion("news_pictures between", value1, value2, "news_pictures");
            return (Criteria) this;
        }

        public Criteria andNews_picturesNotBetween(String value1, String value2) {
            addCriterion("news_pictures not between", value1, value2, "news_pictures");
            return (Criteria) this;
        }

        public Criteria andNews_videoIsNull() {
            addCriterion("news_video is null");
            return (Criteria) this;
        }

        public Criteria andNews_videoIsNotNull() {
            addCriterion("news_video is not null");
            return (Criteria) this;
        }

        public Criteria andNews_videoEqualTo(String value) {
            addCriterion("news_video =", value, "news_video");
            return (Criteria) this;
        }

        public Criteria andNews_videoNotEqualTo(String value) {
            addCriterion("news_video <>", value, "news_video");
            return (Criteria) this;
        }

        public Criteria andNews_videoGreaterThan(String value) {
            addCriterion("news_video >", value, "news_video");
            return (Criteria) this;
        }

        public Criteria andNews_videoGreaterThanOrEqualTo(String value) {
            addCriterion("news_video >=", value, "news_video");
            return (Criteria) this;
        }

        public Criteria andNews_videoLessThan(String value) {
            addCriterion("news_video <", value, "news_video");
            return (Criteria) this;
        }

        public Criteria andNews_videoLessThanOrEqualTo(String value) {
            addCriterion("news_video <=", value, "news_video");
            return (Criteria) this;
        }

        public Criteria andNews_videoLike(String value) {
            addCriterion("news_video like", value, "news_video");
            return (Criteria) this;
        }

        public Criteria andNews_videoNotLike(String value) {
            addCriterion("news_video not like", value, "news_video");
            return (Criteria) this;
        }

        public Criteria andNews_videoIn(List<String> values) {
            addCriterion("news_video in", values, "news_video");
            return (Criteria) this;
        }

        public Criteria andNews_videoNotIn(List<String> values) {
            addCriterion("news_video not in", values, "news_video");
            return (Criteria) this;
        }

        public Criteria andNews_videoBetween(String value1, String value2) {
            addCriterion("news_video between", value1, value2, "news_video");
            return (Criteria) this;
        }

        public Criteria andNews_videoNotBetween(String value1, String value2) {
            addCriterion("news_video not between", value1, value2, "news_video");
            return (Criteria) this;
        }

        public Criteria andNews_encodeIsNull() {
            addCriterion("news_encode is null");
            return (Criteria) this;
        }

        public Criteria andNews_encodeIsNotNull() {
            addCriterion("news_encode is not null");
            return (Criteria) this;
        }

        public Criteria andNews_encodeEqualTo(String value) {
            addCriterion("news_encode =", value, "news_encode");
            return (Criteria) this;
        }

        public Criteria andNews_encodeNotEqualTo(String value) {
            addCriterion("news_encode <>", value, "news_encode");
            return (Criteria) this;
        }

        public Criteria andNews_encodeGreaterThan(String value) {
            addCriterion("news_encode >", value, "news_encode");
            return (Criteria) this;
        }

        public Criteria andNews_encodeGreaterThanOrEqualTo(String value) {
            addCriterion("news_encode >=", value, "news_encode");
            return (Criteria) this;
        }

        public Criteria andNews_encodeLessThan(String value) {
            addCriterion("news_encode <", value, "news_encode");
            return (Criteria) this;
        }

        public Criteria andNews_encodeLessThanOrEqualTo(String value) {
            addCriterion("news_encode <=", value, "news_encode");
            return (Criteria) this;
        }

        public Criteria andNews_encodeLike(String value) {
            addCriterion("news_encode like", value, "news_encode");
            return (Criteria) this;
        }

        public Criteria andNews_encodeNotLike(String value) {
            addCriterion("news_encode not like", value, "news_encode");
            return (Criteria) this;
        }

        public Criteria andNews_encodeIn(List<String> values) {
            addCriterion("news_encode in", values, "news_encode");
            return (Criteria) this;
        }

        public Criteria andNews_encodeNotIn(List<String> values) {
            addCriterion("news_encode not in", values, "news_encode");
            return (Criteria) this;
        }

        public Criteria andNews_encodeBetween(String value1, String value2) {
            addCriterion("news_encode between", value1, value2, "news_encode");
            return (Criteria) this;
        }

        public Criteria andNews_encodeNotBetween(String value1, String value2) {
            addCriterion("news_encode not between", value1, value2, "news_encode");
            return (Criteria) this;
        }

        public Criteria andNews_tendencyIsNull() {
            addCriterion("news_tendency is null");
            return (Criteria) this;
        }

        public Criteria andNews_tendencyIsNotNull() {
            addCriterion("news_tendency is not null");
            return (Criteria) this;
        }

        public Criteria andNews_tendencyEqualTo(String value) {
            addCriterion("news_tendency =", value, "news_tendency");
            return (Criteria) this;
        }

        public Criteria andNews_tendencyNotEqualTo(String value) {
            addCriterion("news_tendency <>", value, "news_tendency");
            return (Criteria) this;
        }

        public Criteria andNews_tendencyGreaterThan(String value) {
            addCriterion("news_tendency >", value, "news_tendency");
            return (Criteria) this;
        }

        public Criteria andNews_tendencyGreaterThanOrEqualTo(String value) {
            addCriterion("news_tendency >=", value, "news_tendency");
            return (Criteria) this;
        }

        public Criteria andNews_tendencyLessThan(String value) {
            addCriterion("news_tendency <", value, "news_tendency");
            return (Criteria) this;
        }

        public Criteria andNews_tendencyLessThanOrEqualTo(String value) {
            addCriterion("news_tendency <=", value, "news_tendency");
            return (Criteria) this;
        }

        public Criteria andNews_tendencyLike(String value) {
            addCriterion("news_tendency like", value, "news_tendency");
            return (Criteria) this;
        }

        public Criteria andNews_tendencyNotLike(String value) {
            addCriterion("news_tendency not like", value, "news_tendency");
            return (Criteria) this;
        }

        public Criteria andNews_tendencyIn(List<String> values) {
            addCriterion("news_tendency in", values, "news_tendency");
            return (Criteria) this;
        }

        public Criteria andNews_tendencyNotIn(List<String> values) {
            addCriterion("news_tendency not in", values, "news_tendency");
            return (Criteria) this;
        }

        public Criteria andNews_tendencyBetween(String value1, String value2) {
            addCriterion("news_tendency between", value1, value2, "news_tendency");
            return (Criteria) this;
        }

        public Criteria andNews_tendencyNotBetween(String value1, String value2) {
            addCriterion("news_tendency not between", value1, value2, "news_tendency");
            return (Criteria) this;
        }

        public Criteria andIs_segedIsNull() {
            addCriterion("is_seged is null");
            return (Criteria) this;
        }

        public Criteria andIs_segedIsNotNull() {
            addCriterion("is_seged is not null");
            return (Criteria) this;
        }

        public Criteria andIs_segedEqualTo(String value) {
            addCriterion("is_seged =", value, "is_seged");
            return (Criteria) this;
        }

        public Criteria andIs_segedNotEqualTo(String value) {
            addCriterion("is_seged <>", value, "is_seged");
            return (Criteria) this;
        }

        public Criteria andIs_segedGreaterThan(String value) {
            addCriterion("is_seged >", value, "is_seged");
            return (Criteria) this;
        }

        public Criteria andIs_segedGreaterThanOrEqualTo(String value) {
            addCriterion("is_seged >=", value, "is_seged");
            return (Criteria) this;
        }

        public Criteria andIs_segedLessThan(String value) {
            addCriterion("is_seged <", value, "is_seged");
            return (Criteria) this;
        }

        public Criteria andIs_segedLessThanOrEqualTo(String value) {
            addCriterion("is_seged <=", value, "is_seged");
            return (Criteria) this;
        }

        public Criteria andIs_segedLike(String value) {
            addCriterion("is_seged like", value, "is_seged");
            return (Criteria) this;
        }

        public Criteria andIs_segedNotLike(String value) {
            addCriterion("is_seged not like", value, "is_seged");
            return (Criteria) this;
        }

        public Criteria andIs_segedIn(List<String> values) {
            addCriterion("is_seged in", values, "is_seged");
            return (Criteria) this;
        }

        public Criteria andIs_segedNotIn(List<String> values) {
            addCriterion("is_seged not in", values, "is_seged");
            return (Criteria) this;
        }

        public Criteria andIs_segedBetween(String value1, String value2) {
            addCriterion("is_seged between", value1, value2, "is_seged");
            return (Criteria) this;
        }

        public Criteria andIs_segedNotBetween(String value1, String value2) {
            addCriterion("is_seged not between", value1, value2, "is_seged");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeEqualTo(Date value) {
            addCriterion("update_time =", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThan(Date value) {
            addCriterion("update_time >", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThan(Date value) {
            addCriterion("update_time <", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIn(List<Date> values) {
            addCriterion("update_time in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andHas_videoIsNull() {
            addCriterion("has_video is null");
            return (Criteria) this;
        }

        public Criteria andHas_videoIsNotNull() {
            addCriterion("has_video is not null");
            return (Criteria) this;
        }

        public Criteria andHas_videoEqualTo(String value) {
            addCriterion("has_video =", value, "has_video");
            return (Criteria) this;
        }

        public Criteria andHas_videoNotEqualTo(String value) {
            addCriterion("has_video <>", value, "has_video");
            return (Criteria) this;
        }

        public Criteria andHas_videoGreaterThan(String value) {
            addCriterion("has_video >", value, "has_video");
            return (Criteria) this;
        }

        public Criteria andHas_videoGreaterThanOrEqualTo(String value) {
            addCriterion("has_video >=", value, "has_video");
            return (Criteria) this;
        }

        public Criteria andHas_videoLessThan(String value) {
            addCriterion("has_video <", value, "has_video");
            return (Criteria) this;
        }

        public Criteria andHas_videoLessThanOrEqualTo(String value) {
            addCriterion("has_video <=", value, "has_video");
            return (Criteria) this;
        }

        public Criteria andHas_videoLike(String value) {
            addCriterion("has_video like", value, "has_video");
            return (Criteria) this;
        }

        public Criteria andHas_videoNotLike(String value) {
            addCriterion("has_video not like", value, "has_video");
            return (Criteria) this;
        }

        public Criteria andHas_videoIn(List<String> values) {
            addCriterion("has_video in", values, "has_video");
            return (Criteria) this;
        }

        public Criteria andHas_videoNotIn(List<String> values) {
            addCriterion("has_video not in", values, "has_video");
            return (Criteria) this;
        }

        public Criteria andHas_videoBetween(String value1, String value2) {
            addCriterion("has_video between", value1, value2, "has_video");
            return (Criteria) this;
        }

        public Criteria andHas_videoNotBetween(String value1, String value2) {
            addCriterion("has_video not between", value1, value2, "has_video");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

		public void setMaxResults(int i) {
			
		}
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

		@Override
		public String toString() {
			return "Criterion [condition=" + condition + ", value=" + value + ", secondValue=" + secondValue
					+ ", noValue=" + noValue + ", singleValue=" + singleValue + ", betweenValue=" + betweenValue
					+ ", listValue=" + listValue + ", typeHandler=" + typeHandler + "]";
		}
    }
}