package com.mwyq.model;

public class TopicTopicRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_topic_relation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_topic_relation.topici_id
     *
     * @mbggenerated
     */
    private String topici_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_topic_relation.topicii_id
     *
     * @mbggenerated
     */
    private String topicii_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_topic_relation.relation
     *
     * @mbggenerated
     */
    private Double relation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_topic_relation.id
     *
     * @return the value of topic_topic_relation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_topic_relation.id
     *
     * @param id the value for topic_topic_relation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_topic_relation.topici_id
     *
     * @return the value of topic_topic_relation.topici_id
     *
     * @mbggenerated
     */
    public String getTopici_id() {
        return topici_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_topic_relation.topici_id
     *
     * @param topici_id the value for topic_topic_relation.topici_id
     *
     * @mbggenerated
     */
    public void setTopici_id(String topici_id) {
        this.topici_id = topici_id == null ? null : topici_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_topic_relation.topicii_id
     *
     * @return the value of topic_topic_relation.topicii_id
     *
     * @mbggenerated
     */
    public String getTopicii_id() {
        return topicii_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_topic_relation.topicii_id
     *
     * @param topicii_id the value for topic_topic_relation.topicii_id
     *
     * @mbggenerated
     */
    public void setTopicii_id(String topicii_id) {
        this.topicii_id = topicii_id == null ? null : topicii_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_topic_relation.relation
     *
     * @return the value of topic_topic_relation.relation
     *
     * @mbggenerated
     */
    public Double getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_topic_relation.relation
     *
     * @param relation the value for topic_topic_relation.relation
     *
     * @mbggenerated
     */
    public void setRelation(Double relation) {
        this.relation = relation;
    }
}