package com.mwyq.model;

public class TopicDocumentRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_document_relation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_document_relation.topic_id
     *
     * @mbggenerated
     */
    private String topic_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_document_relation.news_id
     *
     * @mbggenerated
     */
    private Integer news_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_document_relation.relation
     *
     * @mbggenerated
     */
    private Double relation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_document_relation.id
     *
     * @return the value of topic_document_relation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_document_relation.id
     *
     * @param id the value for topic_document_relation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_document_relation.topic_id
     *
     * @return the value of topic_document_relation.topic_id
     *
     * @mbggenerated
     */
    public String getTopic_id() {
        return topic_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_document_relation.topic_id
     *
     * @param topic_id the value for topic_document_relation.topic_id
     *
     * @mbggenerated
     */
    public void setTopic_id(String topic_id) {
        this.topic_id = topic_id == null ? null : topic_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_document_relation.news_id
     *
     * @return the value of topic_document_relation.news_id
     *
     * @mbggenerated
     */
    public Integer getNews_id() {
        return news_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_document_relation.news_id
     *
     * @param news_id the value for topic_document_relation.news_id
     *
     * @mbggenerated
     */
    public void setNews_id(Integer news_id) {
        this.news_id = news_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_document_relation.relation
     *
     * @return the value of topic_document_relation.relation
     *
     * @mbggenerated
     */
    public Double getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_document_relation.relation
     *
     * @param relation the value for topic_document_relation.relation
     *
     * @mbggenerated
     */
    public void setRelation(Double relation) {
        this.relation = relation;
    }
}