package com.mwyq.model;

import java.util.Date;

public class Topic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic_id
     *
     * @mbggenerated
     */
    private String topic_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topwords
     *
     * @mbggenerated
     */
    private String topwords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic_label_candidate
     *
     * @mbggenerated
     */
    private String topic_label_candidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic_name
     *
     * @mbggenerated
     */
    private String topic_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic_label
     *
     * @mbggenerated
     */
    private String topic_label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.producedtime
     *
     * @mbggenerated
     */
    private Date producedtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.lang_type
     *
     * @mbggenerated
     */
    private String lang_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.keywords
     *
     * @mbggenerated
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic_dir
     *
     * @mbggenerated
     */
    private String topic_dir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic_index
     *
     * @mbggenerated
     */
    private Integer topic_index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.news_count
     *
     * @mbggenerated
     */
    private Integer news_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.news_time
     *
     * @mbggenerated
     */
    private Date news_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.news_content
     *
     * @mbggenerated
     */
    private String news_content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topic_id
     *
     * @return the value of topic.topic_id
     *
     * @mbggenerated
     */
    public String getTopic_id() {
        return topic_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic_id
     *
     * @param topic_id the value for topic.topic_id
     *
     * @mbggenerated
     */
    public void setTopic_id(String topic_id) {
        this.topic_id = topic_id == null ? null : topic_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topwords
     *
     * @return the value of topic.topwords
     *
     * @mbggenerated
     */
    public String getTopwords() {
        return topwords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topwords
     *
     * @param topwords the value for topic.topwords
     *
     * @mbggenerated
     */
    public void setTopwords(String topwords) {
        this.topwords = topwords == null ? null : topwords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topic_label_candidate
     *
     * @return the value of topic.topic_label_candidate
     *
     * @mbggenerated
     */
    public String getTopic_label_candidate() {
        return topic_label_candidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic_label_candidate
     *
     * @param topic_label_candidate the value for topic.topic_label_candidate
     *
     * @mbggenerated
     */
    public void setTopic_label_candidate(String topic_label_candidate) {
        this.topic_label_candidate = topic_label_candidate == null ? null : topic_label_candidate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topic_name
     *
     * @return the value of topic.topic_name
     *
     * @mbggenerated
     */
    public String getTopic_name() {
        return topic_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic_name
     *
     * @param topic_name the value for topic.topic_name
     *
     * @mbggenerated
     */
    public void setTopic_name(String topic_name) {
        this.topic_name = topic_name == null ? null : topic_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topic_label
     *
     * @return the value of topic.topic_label
     *
     * @mbggenerated
     */
    public String getTopic_label() {
        return topic_label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic_label
     *
     * @param topic_label the value for topic.topic_label
     *
     * @mbggenerated
     */
    public void setTopic_label(String topic_label) {
        this.topic_label = topic_label == null ? null : topic_label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.producedtime
     *
     * @return the value of topic.producedtime
     *
     * @mbggenerated
     */
    public Date getProducedtime() {
        return producedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.producedtime
     *
     * @param producedtime the value for topic.producedtime
     *
     * @mbggenerated
     */
    public void setProducedtime(Date producedtime) {
        this.producedtime = producedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.lang_type
     *
     * @return the value of topic.lang_type
     *
     * @mbggenerated
     */
    public String getLang_type() {
        return lang_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.lang_type
     *
     * @param lang_type the value for topic.lang_type
     *
     * @mbggenerated
     */
    public void setLang_type(String lang_type) {
        this.lang_type = lang_type == null ? null : lang_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.keywords
     *
     * @return the value of topic.keywords
     *
     * @mbggenerated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.keywords
     *
     * @param keywords the value for topic.keywords
     *
     * @mbggenerated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topic_dir
     *
     * @return the value of topic.topic_dir
     *
     * @mbggenerated
     */
    public String getTopic_dir() {
        return topic_dir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic_dir
     *
     * @param topic_dir the value for topic.topic_dir
     *
     * @mbggenerated
     */
    public void setTopic_dir(String topic_dir) {
        this.topic_dir = topic_dir == null ? null : topic_dir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topic_index
     *
     * @return the value of topic.topic_index
     *
     * @mbggenerated
     */
    public Integer getTopic_index() {
        return topic_index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic_index
     *
     * @param topic_index the value for topic.topic_index
     *
     * @mbggenerated
     */
    public void setTopic_index(Integer topic_index) {
        this.topic_index = topic_index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.news_count
     *
     * @return the value of topic.news_count
     *
     * @mbggenerated
     */
    public Integer getNews_count() {
        return news_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.news_count
     *
     * @param news_count the value for topic.news_count
     *
     * @mbggenerated
     */
    public void setNews_count(Integer news_count) {
        this.news_count = news_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.news_time
     *
     * @return the value of topic.news_time
     *
     * @mbggenerated
     */
    public Date getNews_time() {
        return news_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.news_time
     *
     * @param news_time the value for topic.news_time
     *
     * @mbggenerated
     */
    public void setNews_time(Date news_time) {
        this.news_time = news_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.news_content
     *
     * @return the value of topic.news_content
     *
     * @mbggenerated
     */
    public String getNews_content() {
        return news_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.news_content
     *
     * @param news_content the value for topic.news_content
     *
     * @mbggenerated
     */
    public void setNews_content(String news_content) {
        this.news_content = news_content == null ? null : news_content.trim();
    }
}