package com.mwyq.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TopicExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topic
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topic
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topic
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    public TopicExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table topic
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andTopic_idIsNull() {
            addCriterion("topic_id is null");
            return (Criteria) this;
        }

        public Criteria andTopic_idIsNotNull() {
            addCriterion("topic_id is not null");
            return (Criteria) this;
        }

        public Criteria andTopic_idEqualTo(String value) {
            addCriterion("topic_id =", value, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idNotEqualTo(String value) {
            addCriterion("topic_id <>", value, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idGreaterThan(String value) {
            addCriterion("topic_id >", value, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idGreaterThanOrEqualTo(String value) {
            addCriterion("topic_id >=", value, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idLessThan(String value) {
            addCriterion("topic_id <", value, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idLessThanOrEqualTo(String value) {
            addCriterion("topic_id <=", value, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idLike(String value) {
            addCriterion("topic_id like", value, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idNotLike(String value) {
            addCriterion("topic_id not like", value, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idIn(List<String> values) {
            addCriterion("topic_id in", values, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idNotIn(List<String> values) {
            addCriterion("topic_id not in", values, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idBetween(String value1, String value2) {
            addCriterion("topic_id between", value1, value2, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopic_idNotBetween(String value1, String value2) {
            addCriterion("topic_id not between", value1, value2, "topic_id");
            return (Criteria) this;
        }

        public Criteria andTopwordsIsNull() {
            addCriterion("topwords is null");
            return (Criteria) this;
        }

        public Criteria andTopwordsIsNotNull() {
            addCriterion("topwords is not null");
            return (Criteria) this;
        }

        public Criteria andTopwordsEqualTo(String value) {
            addCriterion("topwords =", value, "topwords");
            return (Criteria) this;
        }

        public Criteria andTopwordsNotEqualTo(String value) {
            addCriterion("topwords <>", value, "topwords");
            return (Criteria) this;
        }

        public Criteria andTopwordsGreaterThan(String value) {
            addCriterion("topwords >", value, "topwords");
            return (Criteria) this;
        }

        public Criteria andTopwordsGreaterThanOrEqualTo(String value) {
            addCriterion("topwords >=", value, "topwords");
            return (Criteria) this;
        }

        public Criteria andTopwordsLessThan(String value) {
            addCriterion("topwords <", value, "topwords");
            return (Criteria) this;
        }

        public Criteria andTopwordsLessThanOrEqualTo(String value) {
            addCriterion("topwords <=", value, "topwords");
            return (Criteria) this;
        }

        public Criteria andTopwordsLike(String value) {
            addCriterion("topwords like", value, "topwords");
            return (Criteria) this;
        }

        public Criteria andTopwordsNotLike(String value) {
            addCriterion("topwords not like", value, "topwords");
            return (Criteria) this;
        }

        public Criteria andTopwordsIn(List<String> values) {
            addCriterion("topwords in", values, "topwords");
            return (Criteria) this;
        }

        public Criteria andTopwordsNotIn(List<String> values) {
            addCriterion("topwords not in", values, "topwords");
            return (Criteria) this;
        }

        public Criteria andTopwordsBetween(String value1, String value2) {
            addCriterion("topwords between", value1, value2, "topwords");
            return (Criteria) this;
        }

        public Criteria andTopwordsNotBetween(String value1, String value2) {
            addCriterion("topwords not between", value1, value2, "topwords");
            return (Criteria) this;
        }

        public Criteria andTopic_label_candidateIsNull() {
            addCriterion("topic_label_candidate is null");
            return (Criteria) this;
        }

        public Criteria andTopic_label_candidateIsNotNull() {
            addCriterion("topic_label_candidate is not null");
            return (Criteria) this;
        }

        public Criteria andTopic_label_candidateEqualTo(String value) {
            addCriterion("topic_label_candidate =", value, "topic_label_candidate");
            return (Criteria) this;
        }

        public Criteria andTopic_label_candidateNotEqualTo(String value) {
            addCriterion("topic_label_candidate <>", value, "topic_label_candidate");
            return (Criteria) this;
        }

        public Criteria andTopic_label_candidateGreaterThan(String value) {
            addCriterion("topic_label_candidate >", value, "topic_label_candidate");
            return (Criteria) this;
        }

        public Criteria andTopic_label_candidateGreaterThanOrEqualTo(String value) {
            addCriterion("topic_label_candidate >=", value, "topic_label_candidate");
            return (Criteria) this;
        }

        public Criteria andTopic_label_candidateLessThan(String value) {
            addCriterion("topic_label_candidate <", value, "topic_label_candidate");
            return (Criteria) this;
        }

        public Criteria andTopic_label_candidateLessThanOrEqualTo(String value) {
            addCriterion("topic_label_candidate <=", value, "topic_label_candidate");
            return (Criteria) this;
        }

        public Criteria andTopic_label_candidateLike(String value) {
            addCriterion("topic_label_candidate like", value, "topic_label_candidate");
            return (Criteria) this;
        }

        public Criteria andTopic_label_candidateNotLike(String value) {
            addCriterion("topic_label_candidate not like", value, "topic_label_candidate");
            return (Criteria) this;
        }

        public Criteria andTopic_label_candidateIn(List<String> values) {
            addCriterion("topic_label_candidate in", values, "topic_label_candidate");
            return (Criteria) this;
        }

        public Criteria andTopic_label_candidateNotIn(List<String> values) {
            addCriterion("topic_label_candidate not in", values, "topic_label_candidate");
            return (Criteria) this;
        }

        public Criteria andTopic_label_candidateBetween(String value1, String value2) {
            addCriterion("topic_label_candidate between", value1, value2, "topic_label_candidate");
            return (Criteria) this;
        }

        public Criteria andTopic_label_candidateNotBetween(String value1, String value2) {
            addCriterion("topic_label_candidate not between", value1, value2, "topic_label_candidate");
            return (Criteria) this;
        }

        public Criteria andTopic_nameIsNull() {
            addCriterion("topic_name is null");
            return (Criteria) this;
        }

        public Criteria andTopic_nameIsNotNull() {
            addCriterion("topic_name is not null");
            return (Criteria) this;
        }

        public Criteria andTopic_nameEqualTo(String value) {
            addCriterion("topic_name =", value, "topic_name");
            return (Criteria) this;
        }

        public Criteria andTopic_nameNotEqualTo(String value) {
            addCriterion("topic_name <>", value, "topic_name");
            return (Criteria) this;
        }

        public Criteria andTopic_nameGreaterThan(String value) {
            addCriterion("topic_name >", value, "topic_name");
            return (Criteria) this;
        }

        public Criteria andTopic_nameGreaterThanOrEqualTo(String value) {
            addCriterion("topic_name >=", value, "topic_name");
            return (Criteria) this;
        }

        public Criteria andTopic_nameLessThan(String value) {
            addCriterion("topic_name <", value, "topic_name");
            return (Criteria) this;
        }

        public Criteria andTopic_nameLessThanOrEqualTo(String value) {
            addCriterion("topic_name <=", value, "topic_name");
            return (Criteria) this;
        }

        public Criteria andTopic_nameLike(String value) {
            addCriterion("topic_name like", value, "topic_name");
            return (Criteria) this;
        }

        public Criteria andTopic_nameNotLike(String value) {
            addCriterion("topic_name not like", value, "topic_name");
            return (Criteria) this;
        }

        public Criteria andTopic_nameIn(List<String> values) {
            addCriterion("topic_name in", values, "topic_name");
            return (Criteria) this;
        }

        public Criteria andTopic_nameNotIn(List<String> values) {
            addCriterion("topic_name not in", values, "topic_name");
            return (Criteria) this;
        }

        public Criteria andTopic_nameBetween(String value1, String value2) {
            addCriterion("topic_name between", value1, value2, "topic_name");
            return (Criteria) this;
        }

        public Criteria andTopic_nameNotBetween(String value1, String value2) {
            addCriterion("topic_name not between", value1, value2, "topic_name");
            return (Criteria) this;
        }

        public Criteria andTopic_labelIsNull() {
            addCriterion("topic_label is null");
            return (Criteria) this;
        }

        public Criteria andTopic_labelIsNotNull() {
            addCriterion("topic_label is not null");
            return (Criteria) this;
        }

        public Criteria andTopic_labelEqualTo(String value) {
            addCriterion("topic_label =", value, "topic_label");
            return (Criteria) this;
        }

        public Criteria andTopic_labelNotEqualTo(String value) {
            addCriterion("topic_label <>", value, "topic_label");
            return (Criteria) this;
        }

        public Criteria andTopic_labelGreaterThan(String value) {
            addCriterion("topic_label >", value, "topic_label");
            return (Criteria) this;
        }

        public Criteria andTopic_labelGreaterThanOrEqualTo(String value) {
            addCriterion("topic_label >=", value, "topic_label");
            return (Criteria) this;
        }

        public Criteria andTopic_labelLessThan(String value) {
            addCriterion("topic_label <", value, "topic_label");
            return (Criteria) this;
        }

        public Criteria andTopic_labelLessThanOrEqualTo(String value) {
            addCriterion("topic_label <=", value, "topic_label");
            return (Criteria) this;
        }

        public Criteria andTopic_labelLike(String value) {
            addCriterion("topic_label like", value, "topic_label");
            return (Criteria) this;
        }

        public Criteria andTopic_labelNotLike(String value) {
            addCriterion("topic_label not like", value, "topic_label");
            return (Criteria) this;
        }

        public Criteria andTopic_labelIn(List<String> values) {
            addCriterion("topic_label in", values, "topic_label");
            return (Criteria) this;
        }

        public Criteria andTopic_labelNotIn(List<String> values) {
            addCriterion("topic_label not in", values, "topic_label");
            return (Criteria) this;
        }

        public Criteria andTopic_labelBetween(String value1, String value2) {
            addCriterion("topic_label between", value1, value2, "topic_label");
            return (Criteria) this;
        }

        public Criteria andTopic_labelNotBetween(String value1, String value2) {
            addCriterion("topic_label not between", value1, value2, "topic_label");
            return (Criteria) this;
        }

        public Criteria andProducedtimeIsNull() {
            addCriterion("producedtime is null");
            return (Criteria) this;
        }

        public Criteria andProducedtimeIsNotNull() {
            addCriterion("producedtime is not null");
            return (Criteria) this;
        }

        public Criteria andProducedtimeEqualTo(Date value) {
            addCriterionForJDBCDate("producedtime =", value, "producedtime");
            return (Criteria) this;
        }

        public Criteria andProducedtimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("producedtime <>", value, "producedtime");
            return (Criteria) this;
        }

        public Criteria andProducedtimeGreaterThan(Date value) {
            addCriterionForJDBCDate("producedtime >", value, "producedtime");
            return (Criteria) this;
        }

        public Criteria andProducedtimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("producedtime >=", value, "producedtime");
            return (Criteria) this;
        }

        public Criteria andProducedtimeLessThan(Date value) {
            addCriterionForJDBCDate("producedtime <", value, "producedtime");
            return (Criteria) this;
        }

        public Criteria andProducedtimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("producedtime <=", value, "producedtime");
            return (Criteria) this;
        }

        public Criteria andProducedtimeIn(List<Date> values) {
            addCriterionForJDBCDate("producedtime in", values, "producedtime");
            return (Criteria) this;
        }

        public Criteria andProducedtimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("producedtime not in", values, "producedtime");
            return (Criteria) this;
        }

        public Criteria andProducedtimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("producedtime between", value1, value2, "producedtime");
            return (Criteria) this;
        }

        public Criteria andProducedtimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("producedtime not between", value1, value2, "producedtime");
            return (Criteria) this;
        }

        public Criteria andLang_typeIsNull() {
            addCriterion("lang_type is null");
            return (Criteria) this;
        }

        public Criteria andLang_typeIsNotNull() {
            addCriterion("lang_type is not null");
            return (Criteria) this;
        }

        public Criteria andLang_typeEqualTo(String value) {
            addCriterion("lang_type =", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeNotEqualTo(String value) {
            addCriterion("lang_type <>", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeGreaterThan(String value) {
            addCriterion("lang_type >", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeGreaterThanOrEqualTo(String value) {
            addCriterion("lang_type >=", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeLessThan(String value) {
            addCriterion("lang_type <", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeLessThanOrEqualTo(String value) {
            addCriterion("lang_type <=", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeLike(String value) {
            addCriterion("lang_type like", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeNotLike(String value) {
            addCriterion("lang_type not like", value, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeIn(List<String> values) {
            addCriterion("lang_type in", values, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeNotIn(List<String> values) {
            addCriterion("lang_type not in", values, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeBetween(String value1, String value2) {
            addCriterion("lang_type between", value1, value2, "lang_type");
            return (Criteria) this;
        }

        public Criteria andLang_typeNotBetween(String value1, String value2) {
            addCriterion("lang_type not between", value1, value2, "lang_type");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNull() {
            addCriterion("keywords is null");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNotNull() {
            addCriterion("keywords is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordsEqualTo(String value) {
            addCriterion("keywords =", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotEqualTo(String value) {
            addCriterion("keywords <>", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThan(String value) {
            addCriterion("keywords >", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("keywords >=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThan(String value) {
            addCriterion("keywords <", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThanOrEqualTo(String value) {
            addCriterion("keywords <=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLike(String value) {
            addCriterion("keywords like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotLike(String value) {
            addCriterion("keywords not like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsIn(List<String> values) {
            addCriterion("keywords in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotIn(List<String> values) {
            addCriterion("keywords not in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsBetween(String value1, String value2) {
            addCriterion("keywords between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotBetween(String value1, String value2) {
            addCriterion("keywords not between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andTopic_dirIsNull() {
            addCriterion("topic_dir is null");
            return (Criteria) this;
        }

        public Criteria andTopic_dirIsNotNull() {
            addCriterion("topic_dir is not null");
            return (Criteria) this;
        }

        public Criteria andTopic_dirEqualTo(String value) {
            addCriterion("topic_dir =", value, "topic_dir");
            return (Criteria) this;
        }

        public Criteria andTopic_dirNotEqualTo(String value) {
            addCriterion("topic_dir <>", value, "topic_dir");
            return (Criteria) this;
        }

        public Criteria andTopic_dirGreaterThan(String value) {
            addCriterion("topic_dir >", value, "topic_dir");
            return (Criteria) this;
        }

        public Criteria andTopic_dirGreaterThanOrEqualTo(String value) {
            addCriterion("topic_dir >=", value, "topic_dir");
            return (Criteria) this;
        }

        public Criteria andTopic_dirLessThan(String value) {
            addCriterion("topic_dir <", value, "topic_dir");
            return (Criteria) this;
        }

        public Criteria andTopic_dirLessThanOrEqualTo(String value) {
            addCriterion("topic_dir <=", value, "topic_dir");
            return (Criteria) this;
        }

        public Criteria andTopic_dirLike(String value) {
            addCriterion("topic_dir like", value, "topic_dir");
            return (Criteria) this;
        }

        public Criteria andTopic_dirNotLike(String value) {
            addCriterion("topic_dir not like", value, "topic_dir");
            return (Criteria) this;
        }

        public Criteria andTopic_dirIn(List<String> values) {
            addCriterion("topic_dir in", values, "topic_dir");
            return (Criteria) this;
        }

        public Criteria andTopic_dirNotIn(List<String> values) {
            addCriterion("topic_dir not in", values, "topic_dir");
            return (Criteria) this;
        }

        public Criteria andTopic_dirBetween(String value1, String value2) {
            addCriterion("topic_dir between", value1, value2, "topic_dir");
            return (Criteria) this;
        }

        public Criteria andTopic_dirNotBetween(String value1, String value2) {
            addCriterion("topic_dir not between", value1, value2, "topic_dir");
            return (Criteria) this;
        }

        public Criteria andTopic_indexIsNull() {
            addCriterion("topic_index is null");
            return (Criteria) this;
        }

        public Criteria andTopic_indexIsNotNull() {
            addCriterion("topic_index is not null");
            return (Criteria) this;
        }

        public Criteria andTopic_indexEqualTo(Integer value) {
            addCriterion("topic_index =", value, "topic_index");
            return (Criteria) this;
        }

        public Criteria andTopic_indexNotEqualTo(Integer value) {
            addCriterion("topic_index <>", value, "topic_index");
            return (Criteria) this;
        }

        public Criteria andTopic_indexGreaterThan(Integer value) {
            addCriterion("topic_index >", value, "topic_index");
            return (Criteria) this;
        }

        public Criteria andTopic_indexGreaterThanOrEqualTo(Integer value) {
            addCriterion("topic_index >=", value, "topic_index");
            return (Criteria) this;
        }

        public Criteria andTopic_indexLessThan(Integer value) {
            addCriterion("topic_index <", value, "topic_index");
            return (Criteria) this;
        }

        public Criteria andTopic_indexLessThanOrEqualTo(Integer value) {
            addCriterion("topic_index <=", value, "topic_index");
            return (Criteria) this;
        }

        public Criteria andTopic_indexIn(List<Integer> values) {
            addCriterion("topic_index in", values, "topic_index");
            return (Criteria) this;
        }

        public Criteria andTopic_indexNotIn(List<Integer> values) {
            addCriterion("topic_index not in", values, "topic_index");
            return (Criteria) this;
        }

        public Criteria andTopic_indexBetween(Integer value1, Integer value2) {
            addCriterion("topic_index between", value1, value2, "topic_index");
            return (Criteria) this;
        }

        public Criteria andTopic_indexNotBetween(Integer value1, Integer value2) {
            addCriterion("topic_index not between", value1, value2, "topic_index");
            return (Criteria) this;
        }

        public Criteria andNews_countIsNull() {
            addCriterion("news_count is null");
            return (Criteria) this;
        }

        public Criteria andNews_countIsNotNull() {
            addCriterion("news_count is not null");
            return (Criteria) this;
        }

        public Criteria andNews_countEqualTo(Integer value) {
            addCriterion("news_count =", value, "news_count");
            return (Criteria) this;
        }

        public Criteria andNews_countNotEqualTo(Integer value) {
            addCriterion("news_count <>", value, "news_count");
            return (Criteria) this;
        }

        public Criteria andNews_countGreaterThan(Integer value) {
            addCriterion("news_count >", value, "news_count");
            return (Criteria) this;
        }

        public Criteria andNews_countGreaterThanOrEqualTo(Integer value) {
            addCriterion("news_count >=", value, "news_count");
            return (Criteria) this;
        }

        public Criteria andNews_countLessThan(Integer value) {
            addCriterion("news_count <", value, "news_count");
            return (Criteria) this;
        }

        public Criteria andNews_countLessThanOrEqualTo(Integer value) {
            addCriterion("news_count <=", value, "news_count");
            return (Criteria) this;
        }

        public Criteria andNews_countIn(List<Integer> values) {
            addCriterion("news_count in", values, "news_count");
            return (Criteria) this;
        }

        public Criteria andNews_countNotIn(List<Integer> values) {
            addCriterion("news_count not in", values, "news_count");
            return (Criteria) this;
        }

        public Criteria andNews_countBetween(Integer value1, Integer value2) {
            addCriterion("news_count between", value1, value2, "news_count");
            return (Criteria) this;
        }

        public Criteria andNews_countNotBetween(Integer value1, Integer value2) {
            addCriterion("news_count not between", value1, value2, "news_count");
            return (Criteria) this;
        }

        public Criteria andNews_timeIsNull() {
            addCriterion("news_time is null");
            return (Criteria) this;
        }

        public Criteria andNews_timeIsNotNull() {
            addCriterion("news_time is not null");
            return (Criteria) this;
        }

        public Criteria andNews_timeEqualTo(Date value) {
            addCriterion("news_time =", value, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeNotEqualTo(Date value) {
            addCriterion("news_time <>", value, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeGreaterThan(Date value) {
            addCriterion("news_time >", value, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("news_time >=", value, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeLessThan(Date value) {
            addCriterion("news_time <", value, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeLessThanOrEqualTo(Date value) {
            addCriterion("news_time <=", value, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeIn(List<Date> values) {
            addCriterion("news_time in", values, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeNotIn(List<Date> values) {
            addCriterion("news_time not in", values, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeBetween(Date value1, Date value2) {
            addCriterion("news_time between", value1, value2, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_timeNotBetween(Date value1, Date value2) {
            addCriterion("news_time not between", value1, value2, "news_time");
            return (Criteria) this;
        }

        public Criteria andNews_contentIsNull() {
            addCriterion("news_content is null");
            return (Criteria) this;
        }

        public Criteria andNews_contentIsNotNull() {
            addCriterion("news_content is not null");
            return (Criteria) this;
        }

        public Criteria andNews_contentEqualTo(String value) {
            addCriterion("news_content =", value, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentNotEqualTo(String value) {
            addCriterion("news_content <>", value, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentGreaterThan(String value) {
            addCriterion("news_content >", value, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentGreaterThanOrEqualTo(String value) {
            addCriterion("news_content >=", value, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentLessThan(String value) {
            addCriterion("news_content <", value, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentLessThanOrEqualTo(String value) {
            addCriterion("news_content <=", value, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentLike(String value) {
            addCriterion("news_content like", value, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentNotLike(String value) {
            addCriterion("news_content not like", value, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentIn(List<String> values) {
            addCriterion("news_content in", values, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentNotIn(List<String> values) {
            addCriterion("news_content not in", values, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentBetween(String value1, String value2) {
            addCriterion("news_content between", value1, value2, "news_content");
            return (Criteria) this;
        }

        public Criteria andNews_contentNotBetween(String value1, String value2) {
            addCriterion("news_content not between", value1, value2, "news_content");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table topic
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table topic
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}